#!/bin/sh
. /lib/uboot-envtools.sh
. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh
. /lib/rap211g-envtools.sh

mediatek_setup_interfaces()
{
	local board="$1"

	case $board in
	*fpga*)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		ucidef_add_switch "switch0" \
			"0:lan" "1:lan" "2:lan" "3:lan" "4:wan" "6u@eth0" "5u@eth1"
		;;
	*gsw*)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		ucidef_add_switch "switch0" \
			"0:lan" "1:lan" "2:lan" "3:lan" "4:lan" "6u@eth0"
		;;
	*2500wan-p5*)
		ucidef_set_interfaces_lan_wan "lan1 lan2 lan3 lan4" wan
		;;
	senao,iap2300m)
		ucidef_set_interface_wan "eth1"
		;;
	senao,jeap6500)
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		;;
	sonicfi,rap630w-211g)
		ucidef_set_interfaces_lan_wan "lan1 lan2 lan3" eth1
		;;		
	*)	
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		;;
	esac
}

mediatek_setup_macs()
{
	local board="$1"
	local part_name="Factory"
	local lan_mac=""
	local wan_mac=""
	local lan_mac_offset=""
	local wan_mac_offset=""

	case $board in
	edgecore,eap111|\
	edgecore,eap112)
		lan_mac_offset="0x24"
		wan_mac_offset="0x2a"
		;;
	senao,iap2300m|\
	senao,jeap6500)
		hw_mac_addr=$(mtd_get_mac_ascii u-boot-env ethaddr)
		lan_mac="$hw_mac_addr"
		wan_mac=$(macaddr_add $hw_mac_addr 1)
		if [ -n "$lan_mac" ]; then
			ucidef_set_interface_macaddr "lan" "$lan_mac"
		fi
		if [ -n "$wan_mac" ]; then
			ucidef_set_interface_macaddr "wan" "$wan_mac"
			ucidef_set_label_macaddr "$wan_mac"
		fi
		;;
	sonicfi,rap630w-211g)
		sysfs="/sys/class/ieee80211"
		env_dev=$(get_boot_param "boot_param.env_part")
		if [ -n "$env_dev" ]; then
			mtdnum="$( find_mtd_index "$CI_UBIPART" )"
			if [ ! "$mtdnum" ]; then
				echo "cannot find ubi mtd partition $CI_UBIPART"
				return 1
			fi

			ubidev="$( nand_find_ubi "$CI_UBIPART" )"
			if [ ! "$ubidev" ]; then
				ubiattach -m "$mtdnum"
				sync
				ubidev="$( nand_find_ubi "$CI_UBIPART" )"
			fi

			env_ubivol="$( nand_find_volume "${ubidev}" ${env_dev} )"
			if [ -n "${env_ubivol}" ]; then
				#ubootenv_add_uci_config "/dev/$env_ubivol" "0" "0x80000" "0x80000" 1
				echo "/dev/$env_ubivol 0 0x80000 0x80000 1" > /etc/fw_env.config
			fi
		fi
		#echo "/dev/ubi0_0 0 0x80000 0x80000 1" > /etc/fw_env.config
		mac=$(fw_printenv | grep ethaddr | cut -d= -f2)
		wan_mac=$(macaddr_canonicalize $mac)
		[ -z "$mac" ] && return;
		wan_mac=$(macaddr_canonicalize $mac)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		ucidef_set_interface_macaddr "lan" "$lan_mac"
		ucidef_set_interface_macaddr "wan" "$wan_mac"
		ucidef_set_label_macaddr "$wan_mac"
		mac1=$(macaddr_add ${mac} 2)
		mac2=$(macaddr_add ${mac} 3)
		[ -d ${sysfs}/phy0 ] && echo ${mac1} > ${sysfs}/phy0/macaddress
		[ -d ${sysfs}/phy1 ] && echo ${mac2} > ${sysfs}/phy1/macaddress
		return
		;;
	*)
		lan_mac_offset="0x2A"
		wan_mac_offset="0x24"
		;;
	esac

	lan_mac=$(mtd_get_mac_binary $part_name $lan_mac_offset)
	wan_mac=$(mtd_get_mac_binary $part_name $wan_mac_offset)

	case "$lan_mac" in
		00:00:00:00:00:00);;
		ff:ff:ff:ff:ff:ff);;
		*)
		[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" "$lan_mac"
	;;
	esac

	case "$wan_mac" in
		00:00:00:00:00:00);;
		ff:ff:ff:ff:ff:ff);;
		*)
		[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" "$wan_mac"
		[ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
	;;
	esac
}

board_config_update
board=$(board_name)
mediatek_setup_interfaces $board
mediatek_setup_macs $board
board_config_flush

exit 0
