#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case $board in
edgecore,eap112)
        ucidef_add_gpio_switch "gpio_lte_reset" "LTE_reset" "457" "1"
        ucidef_add_gpio_switch "gpio_lte_power" "LTE_power" "458" "1"
        ;;
esac

board_config_flush

exit 0
