#!/bin/sh

cd /tmp
tar xf /tmp/certs.tar
[ -f /tmp/tip-cert/ca.pem -a -f /tmp/tip-cert/client_dec.key -a -f /tmp/tip-cert/client.pem ] || return 1
cp /tmp/tip-cert/ca.pem /tmp/tip-cert/client_dec.key /tmp/tip-cert/client.pem /usr/opensync/certs/

/etc/init.d/opensync restart

return 0

