#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0

. /lib/functions.sh
. /lib/functions/system.sh

caldata_die() {
        echo "caldata: " "$*"
        exit 1
}

caldata_extract() {
        local part=$1
        local offset=$(($2))
        local count=$(($3))
        local mtd

        mtd=$(find_mtd_chardev $part)
        [ -n "$mtd" ] || caldata_die "no mtd device found for partition $part"

        dd if=$mtd of=/lib/firmware/$FIRMWARE iflag=skip_bytes bs=$count skip=$offset count=1 2>/dev/null || \
                caldata_die "failed to extract calibration data from $mtd"
}

ath12k_generate_macs_eap105() {
	touch /lib/firmware/ath12k-macs
	eth=$(cat /sys/class/net/eth0/address)
	mac1=$(macaddr_add $eth 2)
	mac2=$(macaddr_add $eth 3)
	mac3=$(macaddr_add $eth 4)
	echo -ne \\x${mac1//:/\\x} >> /lib/firmware/ath12k-macs
	echo -ne \\x${mac2//:/\\x} >> /lib/firmware/ath12k-macs
	echo -ne \\x${mac3//:/\\x} >> /lib/firmware/ath12k-macs
}

board=$(board_name)

case "$FIRMWARE" in
ath12k/IPQ5332/hw1.0/caldata.bin)
	case "$board" in
	cig,wf189|\
	edgecore,eap105|\
	sercomm,ap72tip)
		caldata_extract "0:ART" 0x1000 0x20000 
		;;
	esac
	;;
ath12k/QCN92XX/hw1.0/cal-pci-0001:01:00.0.bin)
	case "$board" in
	cig,wf189|\
	edgecore,eap105|\
	sercomm,ap72tip)
		caldata_extract "0:ART" 0x58800 0x2d000  
		;;
	esac
	;;
ath12k-macs)
	case "$board" in
	edgecore,eap105)
		ath12k_generate_macs_eap105
		;;
	esac
	;;
*)
	exit 1
	;;
esac
