#!/bin/sh /etc/rc.common
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#
START=98

start_diag_app()
{

        local serverip=`grep -oh "serverip.*#"  /proc/cmdline  | awk -F '#' '{print $2}'`
        local diag_socket_log_path="/usr/sbin/diag_socket_log"
        if [ -f "$diag_socket_log_path" ]; then
                /usr/sbin/diag_socket_log -a $serverip > /dev/null &
                echo "/usr/sbin/diag_socket_log started" > /dev/kmsg
        else
                /usr/sbin/diag_socket_app -a $serverip > /dev/null &
                echo "/usr/sbin/diag_socket_app started" > /dev/kmsg
        fi
}

start() {
	is_ftm=$(grep -E 'wifi_ftm_mode|ath12k_ftm_mode=1' /proc/cmdline | wc -l)
	[ $is_ftm = 1 ] && start_diag_app
}

