#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case $board in
edgecore,eap105)
        ucidef_add_gpio_switch "eth1_phy_reset_down" "eth1_PHY_reset_down" "481" "0"
        ucidef_add_gpio_switch "eth1_phy_reset_up" "eth1_PHY_reset_up" "481" "1"
        ;;
esac

board_config_flush

exit 0
