--- feeds/wifi-ax/ath11k-wifi/Makefile
+++ feeds/wifi-ax/ath11k-wifi/Makefile
@@ -28,6 +28,7 @@ ALLWIFIBOARDS:= \
 	cig-wf188n \
 	cig-wf194c \
 	sercomm-wallaby \
+	yuncore-ax840 \
 	yuncore-ax860
 
 ALLWIFIPACKAGES:=$(foreach BOARD,$(ALLWIFIBOARDS),ath11k-wifi-$(BOARD))
@@ -107,6 +108,7 @@ $(eval $(call generate-ath11k-wifi-package,cig-wf188,Cigtech WF188))
 $(eval $(call generate-ath11k-wifi-package,cig-wf188n,Cigtech WF188n))
 $(eval $(call generate-ath11k-wifi-package,cig-wf194c,Cigtech WF194c))
 $(eval $(call generate-ath11k-wifi-package,sercomm-wallaby,Sercomm Kiwi))
+$(eval $(call generate-ath11k-wifi-package,yuncore-ax840,YunCore AX840))
 $(eval $(call generate-ath11k-wifi-package,yuncore-ax860,YunCore AX860))
 
 $(foreach PACKAGE,$(ALLWIFIPACKAGES),$(eval $(call BuildPackage,$(PACKAGE))))
