#!/bin/sh
[ wan = "$INTERFACE" ] || exit 0
[ "$ACTION" = ifup -o "$ACTION" = ifdown ] || exit 0

[ ifup = "$ACTION" ] && {
	/etc/init.d/apc start
}

[ ifdown = "$ACTION" ] && {
	/etc/init.d/apc stop
}
