#!/bin/sh

. /lib/functions.sh

case "$(board_name)" in
edgecore,ecw5211|\
edgecore,ecw5410)
	MODEL=$(cat /tmp/sysinfo/board_name | sed "s/edgecore,//" | tr [a-z] [A-Z])
	SERIAL=$(cat /sys/class/net/eth0/address | tr -d :)
	PLATFORM=$(cat /tmp/sysinfo/model)
	;;
linksys,ea8300)
	MODEL=$(grep modelNumber= /dev/mtd9 | tr -d '\r\n' | sed "s/modelNumber=//")
	SERIAL=$(grep serial_number= /dev/mtd9 | tr -d '\r\n' | sed "s/serial_number=//")
	PLATFORM=OPENWRT_EA8300
	;;
*)
	MODEL=$(cat /tmp/sysinfo/board_name)
	SERIAL=$(cat /sys/class/net/eth0/address | tr -d :)
	PLATFORM=$(cat /tmp/sysinfo/model)
	;;
esac

MODEL=$(echo $MODEL | sed "s/.*,//" | tr [a-z] [A-Z])

uci set system.tip=tip
uci set system.tip.serial="${SERIAL}"
uci set system.tip.model="${MODEL}"
uci set system.tip.platform="${PLATFORM}"
uci set system.tip.firmware='0.1.0'
uci commit
