#!/bin/sh

CLOUD_IP=

[ -n "$CLOUD_IP" -a -z "$(grep opensync /etc/hosts)" ] && {
	echo $CLOUD_IP opensync-mqtt-broker >> /etc/hosts
	echo $CLOUD_IP opensync-wifi-controller >> /etc/hosts
	echo $CLOUD_IP opensync-redirector.zone1.lab.wlan.tip.build >> /etc/hosts
}
exit 0
