#!/bin/sh
. /usr/share/libubox/jshn.sh
[ "$ACTION" = ifup -o "$ACTION" = ifupdate  -o "$ACTION" = ifdown ] || exit 0

json_init
json_load "$(cat /etc/board.json)"
json_select network
	json_select "wan"
		json_get_vars ifname
	json_select ..
json_select ..

[ -n "$ifname" ] || {
	ifname=$(uci get network.wan.ifname)
	ifname=${ifname%% *}
}

if [ "$ACTION" = ifup -o "$ACTION" = ifupdate ]; then
	vid=$(uci get network.${INTERFACE}.vid)
	net=$(uci get network.${INTERFACE}.ifname)

	[ -z "$net" -o -z "$vid" -o "$vid" = 0 ] && exit 0

	bridge vlan add vid $vid dev br-lan self
	bridge vlan add vid $vid dev br-wan self
	bridge vlan add vid $vid dev $ifname
	bridge vlan add pvid $vid vid $vid dev $net untagged
	exit 0
else
	if [ "$ACTION" = ifdown ]; then
		vid=`echo $INTERFACE | awk -F "_" '{ print $2 }'`
		net=`echo $INTERFACE | awk -F "_" '{ print $1 }'`
		[ -z "$net" -o -z "$vid" -o "$vid" = 0 ] && exit 0

		bridge vlan del vid $vid dev $ifname
		bridge vlan del pvid $vid vid $vid dev $net untagged
		bridge vlan add pvid 1 vid 1 dev $net untagged
		exit 0
	fi
fi
