#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$INTERFACE" = wan ] || [ "$INTERFACE" = lan ] || exit 0

conflict=0
wan_ipaddr="$(ubus call network.interface.wan status | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
lan_ipaddr="$(ubus call network.interface.lan status | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
logger -t hotplug "$ACTION of $INTERFACE ($DEVICE) $wan_ipaddr"

[ "$wan_ipaddr" = "192.168.1" ] && [ "$lan_ipaddr" = "192.168.1" ] && {
    conflict=1
    dest_ip="192.168.0.1"
}
[ "$wan_ipaddr" = "192.168.0" ] && [ "$lan_ipaddr" = "192.168.0" ] && {
    conflict=1
    dest_ip="192.168.1.1"
}
[ $conflict = 1 ] && {
    logger -t hotplug "IP conflict with br-wan.  Switch br-lan to $dest_ip"
    uci set network.lan.ipaddr="$dest_ip"
    uci_commit
    reload_config
}
exit 0
