#!/bin/sh

[ "${INTERFACE:0:4}" == "wlan" ] || exit 0

[ "$ACTION" == remove ] && {
	[ -f /tmp/run/hostapd-cli-$INTERFACE.pid ] && kill "$(cat /tmp/run/hostapd-cli-$INTERFACE.pid)"
	exit 0
}

[ "$ACTION" == add ] && {
	/usr/libexec/ratelimit-wait.sh $INTERFACE &
	exit 0
}
