#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0

. /lib/functions.sh
. /lib/functions/system.sh

ath11k_generate_macs() {
	touch /lib/firmware/ath11k-macs
	eth=$(cat /sys/class/net/eth0/address)
	mac1=$(macaddr_add $eth 2)
	mac2=$(macaddr_add $eth 3)
	mac3=$(macaddr_add $eth 4)
	echo -ne \\x${mac1//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${mac2//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${mac3//:/\\x} >> /lib/firmware/ath11k-macs
}

ath11k_generate_macs_eap101() {
	touch /lib/firmware/ath11k-macs
	eth=$(cat /sys/class/net/eth0/address)
	mac1=$(macaddr_add $eth 4)
	mac2=$(macaddr_add $eth 3)
	mac3=$(macaddr_add $eth 5)
	echo -ne \\x${mac1//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${mac2//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${mac3//:/\\x} >> /lib/firmware/ath11k-macs
}

ath11k_generate_macs_ion4x() {                                     
	touch /lib/firmware/ath11k-macs                           
	wifimac0=$(grep WLAN0_BASEMAC= /dev/mtd15 |cut -d '=' -f2) 
	wifimac1=$(grep WLAN1_BASEMAC= /dev/mtd15 |cut -d '=' -f2) 
	wifimac2=00:00:00:00:00:00                                 
	echo -ne \\x${wifimac0//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${wifimac1//:/\\x} >> /lib/firmware/ath11k-macs
	echo -ne \\x${wifimac2//:/\\x} >> /lib/firmware/ath11k-macs
}

caldata_die() {
        echo "caldata: " "$*"
        exit 1
}

caldata_extract() {
        local part=$1
        local offset=$(($2))
        local count=$(($3))
        local mtd

        mtd=$(find_mtd_chardev $part)
        [ -n "$mtd" ] || caldata_die "no mtd device found for partition $part"

        dd if=$mtd of=/lib/firmware/$FIRMWARE iflag=skip_bytes bs=$count skip=$offset count=1 2>/dev/null || \
                caldata_die "failed to extract calibration data from $mtd"
}

board=$(board_name)

case "$FIRMWARE" in
"ath11k/IPQ6018/hw1.0/caldata.bin")
	case "$board" in
	cig,wf188n|\
	edgecore,eap101|\
	hfcl,ion4xi|\
	hfcl,ion4x|\
	hfcl,ion4x_2|\
	hfcl,ion4xe|\
	wallys,dr6018|\
	wallys,dr6018-v4|\
	yuncore,ax840|\
	yuncore,fap650|\
	glinet,ax1800)
                caldata_extract "0:ART" 0x1000 0x20000  
		;;
	esac
	;;
ath11k/QCN9074/hw1.0/caldata_1.bin)
	case "$board" in
	wallys,dr6018-v4)
                caldata_extract "0:ART" 0x26800 0x20000  
		;;
	esac
	;;
ath11k-macs)
	case "$board" in
	hfcl,ion4xi|\
	hfcl,ion4x|\
	hfcl,ion4x_2|\
	hfcl,ion4xe)                                               
		ath11k_generate_macs_ion4x
		;;
	edgecore,eap101)
		ath11k_generate_macs_eap101
		;;
	cig,wf188n)
		ath11k_generate_macs
		;;
	esac
	;;
*)
	exit 1
	;;
esac
