#!/bin/sh

. /lib/functions/uci-defaults.sh

ipq95xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	qcom,rdp433)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
		;;
	prpl,freedom)
		ucidef_set_interfaces_lan_wan "lan1 lan2 lan3 lan4" "wan"
		;;
	esac
}

board_config_update
board=$(board_name)
ipq95xx_setup_interfaces $board
board_config_flush

exit 0
