#!/bin/sh

band=$1
if [ $band -eq 2 ] || [ $band -eq 3 ]; then
	echo $band > /proc/rf_switch
	echo "firstboot for switch wifi mode 2/3 bands"
	sleep 1
	firstboot -y -r
else
	echo "error band param"
fi
