#!/bin/sh /etc/rc.common

START=60

boot(){
	local bands=$(cat /proc/rf_switch)

	if [ "x$bands" = "x3" ]; then
		echo "AFC is not ready, switch to 2-band mode" >/dev/console
		echo 2 > /proc/rf_switch
		firstboot -y -r
	fi
}
