#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0

. /lib/functions/caldata.sh

board=$(board_name)

case "$FIRMWARE" in
"ath10k/pre-cal-pci-0001:01:00.0.bin")
	case $board in
	edgecore,eap106)
		caldata_extract "0:ART" 0x33000 0x2f20
		;;
	esac
esac
