#!/bin/sh

MAC=$(cat /etc/board.json | jsonfilter -e '@["network"]["wan"]["macaddr"]' | tr -d :)
[ -n "$MAC" ] || MAC=$(cat /sys/class/net/eth0/address | tr -d ":")
uci set system.@system[-1].hostname="OpenAp-${MAC:6}"
uci commit system

exit 0
