#!/bin/sh

fwcfg_symlink() {
	local chip=$1
	local path=$2

	ln -s /lib/firmware/ath10k/fwcfg-${chip}.txt /lib/firmware/ath10k/fwcfg-${path}.txt
}

case "$(board_name)" in
linksys,ea8300)
	fwcfg_symlink ipq4019 ahb-a000000.wifi
	fwcfg_symlink ipq4019 ahb-a800000.wifi
	fwcfg_symlink qca9888 pci-0000:01:00.0
	;;
tp-link,ap2220 |\
tp-link,ec420-g1)
	fwcfg_symlink ipq4019 ahb-a000000.wifi
	fwcfg_symlink qca9888 pci-0000:01:00.0
	;;
edgecore,ecw5211)
	fwcfg_symlink ipq4019 ahb-a000000.wifi
	fwcfg_symlink ipq4019 ahb-a800000.wifi
	;;
esac

exit 0
