#!/bin/sh

uci set network.wan.type=bridge
uci set network.wan6.ifname=@wan
uci set network.wan.metric=1
uci set network.lan.metric=10
uci set network.wan.vlan_filtering=1
uci set network.lan.vlan_filtering=1

# Add LAN ssh rule
uci set firewall.lan_ssh_rule=rule
uci set firewall.lan_ssh_rule.src='lan'
uci set firewall.lan_ssh_rule.target='ACCEPT'
uci set firewall.lan_ssh_rule.proto='tcp'
uci set firewall.lan_ssh_rule.dest_port='22'
uci set firewall.lan_ssh_rule.name="Lan SSH Rule"
uci commit firewall
/etc/init.d/firewall restart

exit 0
