#!/bin/sh

. /lib/functions.sh

SKU="unknown"
MODEL="unknown"
PLATFORM="unknown"
SERIAL="unknown"
MODEL_REV="unknown"
MODEL_DESCR="unknown"
MANUF_NAME="unknown"
MANUF_DATE="unknown"
MANUF_URL="unknown"
MANUF_DESIGN="unknown"
REF_DESIGN="unknown"
CERT_REGION="unknown"
ID="unknown"
#QR_CODE={"DT":"ap","DM":"11:22:33:44:55:66","VN":"EC","SN":"EC2046003718","MN":"ECW5211-L","HW":"R01"}

case "$(board_name)" in
edgecore,ecw5211|\
edgecore,ecw5410)
	MODEL=$(cat /tmp/sysinfo/board_name | sed "s/edgecore,//" | tr [a-z] [A-Z])
	#SERIAL=$(cat /sys/class/net/eth0/address | tr -d :)
	PLATFORM=$(cat /tmp/sysinfo/model)

	SERIAL=$(cat /dev/mtd5 | grep serial_number | cut -d "=" -f2)
	SKU=$(cat /dev/mtd5 | grep sku | cut -d "=" -f2)
	CERT_REGION=$(cat /dev/mtd5 | grep certification_region | cut -d "=" -f2)
	ID=$(cat /dev/mtd5 | grep mac_address | cut -d "=" -f2)
	MANUF_DATE=$(cat /dev/mtd5 | grep manufacturer_date | cut -d "=" -f2)
	MANUF_NAME=$(cat /dev/mtd5 | grep manufacturer_name | cut -d "=" -f2)
	MANUF_URL=$(cat /dev/mtd5 | grep manufacturer_url | cut -d "=" -f2)
	MODEL_DESCR=$(cat /dev/mtd5 | grep model_description | cut -d "=" -f2)
	MODEL_REV=$(cat /dev/mtd5 | grep model_revision | cut -d "=" -f2)
	REF_DESIGN=$(cat /dev/mtd5 | grep reference_design | cut -d "=" -f2)
	;;
cig,wf194c)
	MODEL=$(cat /tmp/sysinfo/board_name)
	SERIAL=$(cat cat /dev/mtd14 | grep BaseMacAddress | cut -dx -f2 | tr -d '\r\n')
	PLATFORM=$(cat /tmp/sysinfo/model)
	;;
linksys,ea8300)
	MODEL=$(grep modelNumber= /dev/mtd9 | tr -d '\r\n' | sed "s/modelNumber=//")
	SERIAL=$(grep serial_number= /dev/mtd9 | tr -d '\r\n' | sed "s/serial_number=//")
	PLATFORM=OPENWRT_EA8300
	MODEL_REV=$(cat /dev/mtd9 | grep hw_revision | cut -d "=" -f2 | tr -d '\r\n')
	MODEL_DESCR=$(cat /dev/mtd9 | grep modelDescription | cut -d "=" -f2 | tr -d '\r\n')
	MANUF_NAME=$(cat /dev/mtd9 | grep "manufacturer=" | cut -d "=" -f2 | tr -d '\r\n')
	MANUF_URL=$(cat /dev/mtd9 | grep manufacturerURL | cut -d "=" -f2 | tr -d '\r\n')
	CERT_REGION=$(cat /dev/mtd9 | grep cert_region | cut -d "=" -f2 | tr -d '\r\n')
	ID=$(cat /dev/mtd9 | grep hw_mac_addr | cut -d "=" -f2 | tr -d '\r\n')

	MANUF_DATE=$(cat /dev/mtd9 | grep manufacturer_date | cut -d "=" -f2 | tr -d '\r\n')
	YEAR=$(echo "$MANUF_DATE" | cut -d "/" -f1)
	MONTH=$(echo "$MANUF_DATE" | cut -d "/" -f2)
	DAY=$(echo "$MANUF_DATE" | cut -d "/" -f3)
	MANUF_DATE="$DAY-$MONTH-$YEAR"
	;;
*)
	MODEL=$(cat /tmp/sysinfo/board_name)
	SERIAL=$(cat /sys/class/net/eth0/address | tr -d :)
	PLATFORM=$(cat /tmp/sysinfo/model)
	;;
esac

MODEL=$(echo $MODEL | sed "s/.*,//" | tr [a-z] [A-Z])

uci set system.tip=tip
uci set system.tip.serial="${SERIAL}"
uci set system.tip.model="${MODEL}"
uci set system.tip.platform="${PLATFORM}"
uci set system.tip.firmware='0.1.0'

uci set system.tip.sku_number="${SKU}"
uci set system.tip.revision="${MODEL_REV}"
uci set system.tip.model_description="${MODEL_DESCR}"
uci set system.tip.manufacturer_name="${MANUF_NAME}"
uci set system.tip.manufacturer_date="${MANUF_DATE}"
uci set system.tip.manufacturer_url="${MANUF_URL}"
uci set system.tip.reference_design="${REF_DESIGN}"
uci set system.tip.certification_region="${CERT_REGION}"
uci set system.tip.id="${ID}"
#uci set system.tip.qr_code="${QR_CODE}"

uci commit
