#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018 rosysong@rosinson.com
#

. /lib/nft-qos/core.sh
. /lib/nft-qos/ssid_ratelimit.sh

START=99
USE_PROCD=1

service_triggers() {

	procd_open_validate
	procd_close_validate
}

start_service() {
	config_load nft-qos
	qosdef_flush_ssid_ratelimit
	qosdef_init_ssid_ratelimit
	qosdef_init_done
	qosdef_start
}

stop_service() {
	qosdef_flush_ssid_ratelimit
	qosdef_clean_cache
}
