#!/bin/sh

. /lib/functions.sh

board=$(board_name)
case $board in
	sonicfi,rap630w-311g|\
	cybertan,eww631-b1)
		for num in $(seq 1 3)
		do
			uci add poe port
			uci set poe.@port[-1]='port'
			eval uci set poe.@port[-1].port_num='${num}'
			uci set poe.@port[-1].admin_mode='1'
		done
		uci commit
		;;
	*)
		;;
esac