#!/bin/sh

wan=$(cat /etc/board.json | jsonfilter -e '@.network.wan.device')
[ -z "$wan" ] && eval $(jsonfilter -i /etc/board.json -e 'wan=@.network.wan.ports.*')
for w in $wan; do
	uci add_list event.config.wan_port=$w
done
