#!/bin/sh

. /lib/functions.sh

case "$(board_name)" in
	"edgecore,oap101"|\
	"edgecore,oap101e"|\
	"edgecore,oap101-6e"|\
	"edgecore,oap101e-6e")
		uci set gps.@gps[-1].tty='ttyMSM1'
		uci set gps.@gps[-1].adjust_time=0
		uci set gps.@gps[-1].disabled=0
		uci set gps.@gps[-1].baudrate=115200
		;;
esac

exit 0
