#!/bin/sh

CFG=/etc/board.json

[ -s $CFG ] || /bin/board_detect || exit 1

model_name=$(cat ${CFG} | jsonfilter -e '@.model.id')

if [ ${model_name} == "edgecore,eap111" ]; then
    # eth0: lan
    uci add network device
    uci set network.@device[-1].name='eth0'
    uci set network.@device[-1].macaddr=$(cat ${CFG}  | jsonfilter -e '@.network.lan.macaddr')

    # eth1: wan
    uci add network device
    uci set network.@device[-1].name='eth1'
    uci set network.@device[-1].macaddr=$(cat ${CFG}  | jsonfilter -e '@.network.wan.macaddr')

    uci commit network
fi
