#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
cig,wf194c4)
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth0" "tx rx link"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	;;
edgecore,eap102)
	ucidef_set_led_netdev "poe" "poe" "green:wan" "eth0"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	;;
esac

board_config_flush

exit 0
