#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

qcom_setup_interfaces()
{
	local board="$1"
	ucidef_add_switch "switch0"
	ucidef_add_switch_attr "switch0" "enable" "false"
	ucidef_add_switch_attr "switch0" "reset" "false"

	case $board in
	tplink,ex227|\
	tplink,ex447)
		ucidef_set_interface_wan "eth0"
		ucidef_set_interface_lan ""
		;;
	cig,wf194c4)
		ucidef_set_interface_lan "eth0"
		ucidef_set_interface_wan "eth1"
		;;
	edgecore,eap102|\
	cig,wf196)
		ucidef_set_interface_lan "eth1"
		ucidef_set_interface_wan "eth0"
		;;
	esac
}

qcom_setup_macs()
{
	local board="$1"

	case $board in
	cig,wf194c4|\
	cig,wf196)
		mtd=$(find_mtd_chardev "0:APPSBLENV")
		[ -z "$mtd" ] && return;
		mac=$(grep BaseMacAddress= $mtd | cut -dx -f2)
		[ -z "$mac" ] && return;
		wan_mac=$(macaddr_canonicalize $mac)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		ucidef_set_network_device_mac eth0 $lan_mac
		ucidef_set_network_device_mac eth1 $wan_mac
		ucidef_set_label_macaddr $wan_mac
		;;
	*)
		wan_mac=$(cat /sys/class/net/eth0/address)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		;;
	esac
	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
	[ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
}

board_config_update
board=$(board_name)
qcom_setup_interfaces $board
qcom_setup_macs $board
board_config_flush

exit 0
