#include <stdio.h>
#include "unity.h" 

void testUnitySizeInitializationReminder(void);
void testPassShouldEndImmediatelyWithPass(void);
void testTrue(void);
void testFalse(void);
void testPreviousPass(void);
void testNotVanilla(void);
void testNotTrue(void);
void testNotFalse(void);
void testNotUnless(void);
void testNotNotEqual(void);
void testFail(void);
void testIsNull(void);
void testIsNullShouldFailIfNot(void);
void testNotNullShouldFailIfNULL(void);
void testIgnore(void);
void testIgnoreMessage(void);
void testNotEqualInts(void);
void testNotEqualInt8s(void);
void testNotEqualInt16s(void);
#if 0
void testNotEqualInt32s(void);
#endif
void testNotEqualBits(void);
void testNotEqualUInts(void);
void testNotEqualUInt8s(void);
void testNotEqualUInt16s(void);
#if 0
void testNotEqualUInt32s(void);
#endif
void testNotEqualHex8s(void);
void testNotEqualHex8sIfSigned(void);
void testNotEqualHex16s(void);
void testNotEqualHex16sIfSigned(void);
void testNotEqualHex32s(void);
void testNotEqualHex32sIfSigned(void);
void testEqualInts(void);
void testEqualInt8s(void);
void testEqualInt8sWhenThereAreDifferencesOutside8Bits(void);
void testEqualInt16s(void);
void testEqualInt16sNegatives(void);
void testEqualInt16sWhenThereAreDifferencesOutside16Bits(void);
void testEqualInt32s(void);
void testEqualInt32sNegatives(void);
void testEqualUints(void);
void testEqualUint8s(void);
void testEqualUint8sWhenThereAreDifferencesOutside8Bits(void);
void testEqualUint16s(void);
void testEqualUint16sWhenThereAreDifferencesOutside16Bits(void);
void testEqualUint32s(void);
void testNotEqual(void);
void testEqualHex8s(void);
void testEqualHex8sWhenThereAreDifferencesOutside8Bits(void);
void testEqualHex8sNegatives(void);
void testEqualHex16s(void);
void testEqualHex16sWhenThereAreDifferencesOutside16Bits(void);
void testEqualHex32s(void);
void testEqualBits(void);
void testNotEqualBitHigh(void);
void testNotEqualBitLow(void);
void testNotEqualBitsHigh(void);
void testNotEqualBitsLow(void);
void testEqualShorts(void);
void testEqualUShorts(void);
void testEqualChars(void);
void testEqualUChars(void);
void testEqualPointers(void);
void testNotEqualPointers(void);
void testIntsWithinDelta(void);
void testIntsWithinDeltaAndCustomMessage(void);
void testIntsNotWithinDelta(void);
void testIntsNotWithinDeltaAndCustomMessage(void);
void testUIntsWithinDelta(void);
void testUIntsWithinDeltaAndCustomMessage(void);
void testUIntsNotWithinDelta(void);
void testUIntsNotWithinDeltaAndCustomMessage(void);
void testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassSmallFirst(void);
void testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassSmallFirstAndCustomMessage(void);
void testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassBigFirst(void);
void testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassBigFirstAndCustomMessage(void);
void testHEX32sWithinDelta(void);
void testHEX32sWithinDeltaAndCustomMessage(void);
void testHEX32sNotWithinDelta(void);
void testHEX32sNotWithinDeltaAndCustomMessage(void);
void testHEX32sNotWithinDeltaEvenThoughASignedIntWouldPass(void);
void testHEX32sNotWithinDeltaEvenThoughASignedIntWouldPassAndCustomMessage(void);
void testHEX16sWithinDelta(void);
void testHEX16sWithinDeltaAndCustomMessage(void);
void testHEX16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits(void);
void testHEX16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage(void);
void testHEX16sNotWithinDelta(void);
void testHEX16sNotWithinDeltaAndCustomMessage(void);
void testHEX8sWithinDelta(void);
void testHEX8sWithinDeltaAndCustomMessage(void);
void testHEX8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits(void);
void testHEX8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage(void);
void testHEX8sNotWithinDelta(void);
void testHEX8sNotWithinDeltaAndCustomMessage(void);
void testUINT32sWithinDelta(void);
void testUINT32sWithinDeltaAndCustomMessage(void);
void testUINT32sNotWithinDelta(void);
void testUINT32sNotWithinDeltaAndCustomMessage(void);
void testUINT32sNotWithinDeltaEvenThoughASignedIntWouldPass(void);
void testUINT32sNotWithinDeltaEvenThoughASignedIntWouldPassAndCustomMessage(void);
void testUINT16sWithinDelta(void);
void testUINT16sWithinDeltaAndCustomMessage(void);
void testUINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits(void);
void testUINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage(void);
void testUINT16sNotWithinDelta(void);
void testUINT16sNotWithinDeltaAndCustomMessage(void);
void testUINT8sWithinDelta(void);
void testUINT8sWithinDeltaAndCustomMessage(void);
void testUINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits(void);
void testUINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage(void);
void testUINT8sNotWithinDelta(void);
void testUINT8sNotWithinDeltaAndCustomMessage(void);
void testINT32sWithinDelta(void);
void testINT32sWithinDeltaAndCustomMessage(void);
void testINT32sNotWithinDelta(void);
void testINT32sNotWithinDeltaAndDifferenceOverflows(void);
void testINT32sNotWithinDeltaAndCustomMessage(void);
void testINT16sWithinDelta(void);
void testINT16sWithinDeltaAndCustomMessage(void);
void testINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits(void);
void testINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage(void);
void testINT16sNotWithinDelta(void);
void testINT16sNotWithinDeltaAndCustomMessage(void);
void testINT8sWithinDelta(void);
void testINT8sWithinDeltaAndCustomMessage(void);
void testINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits(void);
void testINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage(void);
void testINT8sNotWithinDelta(void);
void testINT8sNotWithinDeltaAndCustomMessage(void);
void testEqualStrings(void);
void testEqualStringsLen(void);
void testEqualStringsWithCarriageReturnsAndLineFeeds(void);
void testNotEqualString1(void);
void testNotEqualStringLen1(void);
void testNotEqualString2(void);
void testNotEqualStringLen2(void);
void testNotEqualString3(void);
void testNotEqualStringLen3(void);
void testNotEqualString4(void);
void testNotEqualStringLen4(void);
void testNotEqualString5(void);
void testNotEqualString_ExpectedStringIsNull(void);
void testNotEqualStringLen_ExpectedStringIsNull(void);
void testNotEqualString_ActualStringIsNull(void);
void testNotEqualStringLen_ActualStringIsNull(void);
void testEqualStringArrays(void);
void testNotEqualStringArray1(void);
void testNotEqualStringArray2(void);
void testNotEqualStringArray3(void);
void testNotEqualStringArray4(void);
void testNotEqualStringArray5(void);
void testNotEqualStringArray6(void);
void testEqualStringArrayIfBothNulls(void);
void testNotEqualStringArrayLengthZero(void);
void testEqualStringEachEqual(void);
void testNotEqualStringEachEqual1(void);
void testNotEqualStringEachEqual2(void);
void testNotEqualStringEachEqual3(void);
void testNotEqualStringEachEqual4(void);
void testNotEqualStringEachEqual5(void);
void testEqualMemory(void);
void testNotEqualMemory1(void);
void testNotEqualMemory2(void);
void testNotEqualMemory3(void);
void testNotEqualMemory4(void);
void testNotEqualMemoryLengthZero(void);
void testEqualIntArrays(void);
void testNotEqualIntArraysNullExpected(void);
void testNotEqualIntArraysNullActual(void);
void testNotEqualIntArrays1(void);
void testNotEqualIntArrays2(void);
void testNotEqualIntArrays3(void);
void testNotEqualIntArraysLengthZero(void);
void testEqualIntEachEqual(void);
void testNotEqualIntEachEqualNullActual(void);
void testNotEqualIntEachEqual1(void);
void testNotEqualIntEachEqual2(void);
void testNotEqualIntEachEqual3(void);
void testNotEqualEachEqualLengthZero(void);
void testEqualPtrArrays(void);
void testNotEqualPtrArraysNullExpected(void);
void testNotEqualPtrArraysNullActual(void);
void testNotEqualPtrArrays1(void);
void testNotEqualPtrArrays2(void);
void testNotEqualPtrArrays3(void);
void testEqualPtrEachEqual(void);
void testNotEqualPtrEachEqualNullExpected(void);
void testNotEqualPtrEachEqualNullActual(void);
void testNotEqualPtrEachEqual1(void);
void testNotEqualPtrEachEqual2(void);
void testNotEqualPtrEachEqual3(void);
void testEqualInt8Arrays(void);
void testNotEqualInt8Arrays(void);
void testEqualInt8EachEqual(void);
void testNotEqualInt8EachEqual(void);
void testEqualUIntArrays(void);
void testNotEqualUIntArrays1(void);
void testNotEqualUIntArrays2(void);
void testNotEqualUIntArrays3(void);
void testEqualUIntEachEqual(void);
void testNotEqualUIntEachEqual1(void);
void testNotEqualUIntEachEqual2(void);
void testNotEqualUIntEachEqual3(void);
void testEqualInt16Arrays(void);
void testNotEqualInt16Arrays(void);
void testEqualInt16EachEqual(void);
void testNotEqualInt16EachEqual(void);
void testEqualInt32Arrays(void);
void testNotEqualInt32Arrays(void);
void testEqualInt32EachEqual(void);
void testNotEqualInt32EachEqual(void);
void testEqualUINT8Arrays(void);
void testNotEqualUINT8Arrays1(void);
void testNotEqualUINT8Arrays2(void);
void testNotEqualUINT8Arrays3(void);
void testEqualUINT16Arrays(void);
void testNotEqualUINT16Arrays1(void);
void testNotEqualUINT16Arrays2(void);
void testNotEqualUINT16Arrays3(void);
void testEqualUINT32Arrays(void);
void testNotEqualUINT32Arrays1(void);
void testNotEqualUINT32Arrays2(void);
void testNotEqualUINT32Arrays3(void);
void testEqualHEXArrays(void);
void testNotEqualHEXArrays1(void);
void testNotEqualHEXArrays2(void);
void testNotEqualHEXArrays3(void);
void testEqualHEX32Arrays(void);
void testNotEqualHEX32Arrays1(void);
void testNotEqualHEX32Arrays2(void);
void testNotEqualHEX32Arrays3(void);
void testEqualHEX16Arrays(void);
void testNotEqualHEX16Arrays1(void);
void testNotEqualHEX16Arrays2(void);
void testNotEqualHEX16Arrays3(void);
void testEqualHEX8Arrays(void);
void testNotEqualHEX8Arrays1(void);
void testNotEqualHEX8Arrays2(void);
void testNotEqualHEX8Arrays3(void);
void testEqualUINT8EachEqual(void);
void testNotEqualUINT8EachEqual1(void);
void testNotEqualUINT8EachEqual2(void);
void testNotEqualUINT8EachEqual3(void);
void testEqualUINT16EachEqual(void);
void testNotEqualUINT16EachEqual1(void);
void testNotEqualUINT16EachEqual2(void);
void testNotEqualUINT16EachEqual3(void);
void testEqualUINT32EachEqual(void);
void testNotEqualUINT32EachEqual1(void);
void testNotEqualUINT32EachEqual2(void);
void testNotEqualUINT32EachEqual3(void);
void testEqualHEXEachEqual(void);
void testNotEqualHEXEachEqual1(void);
void testNotEqualHEXEachEqual2(void);
void testNotEqualHEXEachEqual3(void);
void testEqualHEX32EachEqual(void);
void testNotEqualHEX32EachEqual1(void);
void testNotEqualHEX32EachEqual2(void);
void testNotEqualHEX32EachEqual3(void);
void testEqualHEX16EachEqual(void);
void testNotEqualHEX16EachEqual1(void);
void testNotEqualHEX16EachEqual2(void);
void testNotEqualHEX16EachEqual3(void);
void testEqualHEX8EachEqual(void);
void testNotEqualHEX8EachEqual1(void);
void testNotEqualHEX8EachEqual2(void);
void testNotEqualHEX8EachEqual3(void);
void testEqualMemoryArrays(void);
void testNotEqualMemoryArraysExpectedNull(void);
void testNotEqualMemoryArraysActualNull(void);
void testNotEqualMemoryArrays1(void);
void testNotEqualMemoryArrays2(void);
void testNotEqualMemoryArrays3(void);
void testEqualMemoryEachEqual(void);
void testNotEqualMemoryEachEqualExpectedNull(void);
void testNotEqualMemoryEachEqualActualNull(void);
void testNotEqualMemoryEachEqual1(void);
void testNotEqualMemoryEachEqual2(void);
void testNotEqualMemoryEachEqual3(void);
void testProtection(void);
void testIgnoredAndThenFailInTearDown(void);
void testFailureCountIncrementsAndIsReturnedAtEnd(void);
void testCstringsEscapeSequence(void);
void testHexPrintsUpToMaxNumberOfNibbles(void);
void testPrintNumbers32(void);
void testPrintNumbersUnsigned32(void);
void testPrintNumbersInt64(void);
void testPrintNumbersUInt64(void);
void testEqualHex64s(void);
void testEqualUint64s(void);
void testEqualInt64s(void);
void testNotEqualHex64s(void);
void testNotEqualUint64s(void);
void testNotEqualInt64s(void);
void testNotEqualHex64sIfSigned(void);
void testHEX64sWithinDelta(void);
void testHEX64sNotWithinDelta(void);
void testHEX64sNotWithinDeltaEvenThoughASignedIntWouldPass(void);
void testUINT64sWithinDelta(void);
void testUINT64sNotWithinDelta(void);
void testUINT64sNotWithinDeltaEvenThoughASignedIntWouldPass(void);
void testINT64sWithinDelta(void);
void testINT64sNotWithinDelta(void);
void testINT64sNotWithinDeltaAndDifferenceOverflows(void);
void testEqualHEX64Arrays(void);
void testEqualUint64Arrays(void);
void testEqualInt64Arrays(void);
void testNotEqualHEX64Arrays1(void);
void testNotEqualHEX64Arrays2(void);
void testNotEqualUint64Arrays(void);
void testNotEqualInt64Arrays(void);
void testFloatsWithinDelta(void);
void testFloatsNotWithinDelta(void);
void testFloatsEqual(void);
void testFloatsNotEqual(void);
void testFloatsNotEqualNegative1(void);
void testFloatsNotEqualNegative2(void);
void testFloatsNotEqualActualNaN(void);
void testFloatsNotEqualExpectedNaN(void);
void testFloatsEqualBothNaN(void);
void testFloatsNotEqualInfNaN(void);
void testFloatsNotEqualNaNInf(void);
void testFloatsNotEqualActualInf(void);
void testFloatsNotEqualExpectedInf(void);
void testFloatsEqualBothInf(void);
void testFloatsNotEqualPlusMinusInf(void);
void testFloatIsPosInf1(void);
void testFloatIsPosInf2(void);
void testFloatIsNegInf1(void);
void testFloatIsNegInf2(void);
void testFloatIsNotPosInf1(void);
void testFloatIsNotPosInf2(void);
void testFloatIsNotNegInf(void);
void testFloatIsNan1(void);
void testFloatIsNan2(void);
void testFloatIsNotNan1(void);
void testFloatIsNotNan2(void);
void testFloatInfIsNotNan(void);
void testFloatNanIsNotInf(void);
void testFloatIsDeterminate1(void);
void testFloatIsDeterminate2(void);
void testFloatIsNotDeterminate1(void);
void testFloatIsNotDeterminate2(void);
void testFloatTraitFailsOnInvalidTrait(void);
void testEqualFloatArrays(void);
void testNotEqualFloatArraysExpectedNull(void);
void testNotEqualFloatArraysActualNull(void);
void testNotEqualFloatArrays1(void);
void testNotEqualFloatArrays2(void);
void testNotEqualFloatArrays3(void);
void testNotEqualFloatArraysNegative1(void);
void testNotEqualFloatArraysNegative2(void);
void testNotEqualFloatArraysNegative3(void);
void testEqualFloatArraysNaN(void);
void testEqualFloatArraysInf(void);
void testNotEqualFloatArraysLengthZero(void);
void testEqualFloatEachEqual(void);
void testNotEqualFloatEachEqualActualNull(void);
void testNotEqualFloatEachEqual1(void);
void testNotEqualFloatEachEqual2(void);
void testNotEqualFloatEachEqual3(void);
void testNotEqualFloatEachEqualNegative1(void);
void testNotEqualFloatEachEqualNegative2(void);
void testNotEqualFloatEachEqualNegative3(void);
void testEqualFloatEachEqualNaN(void);
void testEqualFloatEachEqualInf(void);
void testNotEqualFloatEachEqualLengthZero(void);
void testFloatPrinting(void);
void testFloatPrintingRoundTiesToEven(void);
void testFloatPrintingInfinityAndNaN(void);
void testAllFloatPrintingPart1_LessThan32Bits(void);
void testAllFloatPrintingPart2_Larger(void);
void testAllFloatPrintingPart3_LargerStill(void);
void testDoublesWithinDelta(void);
void testDoublesNotWithinDelta(void);
void testDoublesEqual(void);
void testDoublesNotEqual(void);
void testDoublesNotEqualNegative1(void);
void testDoublesNotEqualNegative2(void);
void testDoublesNotEqualActualNaN(void);
void testDoublesNotEqualExpectedNaN(void);
void testDoublesEqualBothNaN(void);
void testDoublesNotEqualInfNaN(void);
void testDoublesNotEqualNaNInf(void);
void testDoublesNotEqualActualInf(void);
void testDoublesNotEqualExpectedInf(void);
void testDoublesEqualBothInf(void);
void testDoublesNotEqualPlusMinusInf(void);
void testDoubleIsPosInf1(void);
void testDoubleIsPosInf2(void);
void testDoubleIsNegInf1(void);
void testDoubleIsNegInf2(void);
void testDoubleIsNotPosInf1(void);
void testDoubleIsNotPosInf2(void);
void testDoubleIsNotNegInf(void);
void testDoubleIsNan1(void);
void testDoubleIsNan2(void);
void testDoubleIsNotNan1(void);
void testDoubleIsNotNan2(void);
void testDoubleInfIsNotNan(void);
void testDoubleNanIsNotInf(void);
void testDoubleIsDeterminate1(void);
void testDoubleIsDeterminate2(void);
void testDoubleIsNotDeterminate1(void);
void testDoubleIsNotDeterminate2(void);
void testDoubleTraitFailsOnInvalidTrait(void);
void testEqualDoubleArrays(void);
void testNotEqualDoubleArraysExpectedNull(void);
void testNotEqualDoubleArraysActualNull(void);
void testNotEqualDoubleArrays1(void);
void testNotEqualDoubleArrays2(void);
void testNotEqualDoubleArrays3(void);
void testNotEqualDoubleArraysNegative1(void);
void testNotEqualDoubleArraysNegative2(void);
void testNotEqualDoubleArraysNegative3(void);
void testEqualDoubleArraysNaN(void);
void testEqualDoubleArraysInf(void);
void testNotEqualDoubleArraysLengthZero(void);
void testEqualDoubleEachEqual(void);
void testNotEqualDoubleEachEqualActualNull(void);
void testNotEqualDoubleEachEqual1(void);
void testNotEqualDoubleEachEqual2(void);
void testNotEqualDoubleEachEqual3(void);
void testNotEqualDoubleEachEqualNegative1(void);
void testNotEqualDoubleEachEqualNegative2(void);
void testNotEqualDoubleEachEqualNegative3(void);
void testEqualDoubleEachEqualNaN(void);
void testEqualDoubleEachEqualInf(void);
void testNotEqualDoubleEachEqualLengthZero(void);
void testDoublePrinting(void);
void testDoublePrintingRoundTiesToEven(void);
void testDoublePrintingInfinityAndNaN(void);
void testThatDetailsCanBeHandleOneDetail(void);
void testThatDetailsCanHandleTestFail(void);
void testThatDetailsCanBeHandleTwoDetails(void);
void testThatDetailsCanBeHandleSingleDetailClearingTwoDetails(void);



int main(void)
{
    UnityBegin("testunityrunner ");

    RUN_TEST(testUnitySizeInitializationReminder);
    RUN_TEST(testPassShouldEndImmediatelyWithPass);
    RUN_TEST(testTrue);
    RUN_TEST(testFalse);
    RUN_TEST(testPreviousPass);
    RUN_TEST(testNotVanilla);
    RUN_TEST(testNotTrue);
    RUN_TEST(testNotFalse);
    RUN_TEST(testNotUnless);
    RUN_TEST(testNotNotEqual);
    RUN_TEST(testFail);
    RUN_TEST(testIsNull);
    RUN_TEST(testIsNullShouldFailIfNot);
    RUN_TEST(testNotNullShouldFailIfNULL);
    RUN_TEST(testIgnore);
    RUN_TEST(testIgnoreMessage);
    RUN_TEST(testNotEqualInts);
    RUN_TEST(testNotEqualInt8s);
    RUN_TEST(testNotEqualInt16s);
#if 0
    RUN_TEST(testNotEqualInt32s);
#endif
    RUN_TEST(testNotEqualBits);
    RUN_TEST(testNotEqualUInts);
    RUN_TEST(testNotEqualUInt8s);
    RUN_TEST(testNotEqualUInt16s);
#if 0
    RUN_TEST(testNotEqualUInt32s);
#endif
    RUN_TEST(testNotEqualHex8s);
    RUN_TEST(testNotEqualHex8sIfSigned);
    RUN_TEST(testNotEqualHex16s);
    RUN_TEST(testNotEqualHex16sIfSigned);
    RUN_TEST(testNotEqualHex32s);
    RUN_TEST(testNotEqualHex32sIfSigned);
    RUN_TEST(testEqualInts);
    RUN_TEST(testEqualInt8s);
    RUN_TEST(testEqualInt8sWhenThereAreDifferencesOutside8Bits);
    RUN_TEST(testEqualInt16s);
    RUN_TEST(testEqualInt16sNegatives);
    RUN_TEST(testEqualInt16sWhenThereAreDifferencesOutside16Bits);
    RUN_TEST(testEqualInt32s);
    RUN_TEST(testEqualInt32sNegatives);
    RUN_TEST(testEqualUints);
    RUN_TEST(testEqualUint8s);
    RUN_TEST(testEqualUint8sWhenThereAreDifferencesOutside8Bits);
    RUN_TEST(testEqualUint16s);
    RUN_TEST(testEqualUint16sWhenThereAreDifferencesOutside16Bits);
    RUN_TEST(testEqualUint32s);
    RUN_TEST(testNotEqual);
    RUN_TEST(testEqualHex8s);
    RUN_TEST(testEqualHex8sWhenThereAreDifferencesOutside8Bits);
    RUN_TEST(testEqualHex8sNegatives);
    RUN_TEST(testEqualHex16s);
    RUN_TEST(testEqualHex16sWhenThereAreDifferencesOutside16Bits);
    RUN_TEST(testEqualHex32s);
    RUN_TEST(testEqualBits);
    RUN_TEST(testNotEqualBitHigh);
    RUN_TEST(testNotEqualBitLow);
    RUN_TEST(testNotEqualBitsHigh);
    RUN_TEST(testNotEqualBitsLow);
    RUN_TEST(testEqualShorts);
    RUN_TEST(testEqualUShorts);
    RUN_TEST(testEqualChars);
    RUN_TEST(testEqualUChars);
    RUN_TEST(testEqualPointers);
    RUN_TEST(testNotEqualPointers);
    RUN_TEST(testIntsWithinDelta);
    RUN_TEST(testIntsWithinDeltaAndCustomMessage);
    RUN_TEST(testIntsNotWithinDelta);
    RUN_TEST(testIntsNotWithinDeltaAndCustomMessage);
    RUN_TEST(testUIntsWithinDelta);
    RUN_TEST(testUIntsWithinDeltaAndCustomMessage);
    RUN_TEST(testUIntsNotWithinDelta);
    RUN_TEST(testUIntsNotWithinDeltaAndCustomMessage);
    RUN_TEST(testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassSmallFirst);
    RUN_TEST(testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassSmallFirstAndCustomMessage);
    RUN_TEST(testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassBigFirst);
    RUN_TEST(testUIntsNotWithinDeltaEvenThoughASignedIntWouldPassBigFirstAndCustomMessage);
    RUN_TEST(testHEX32sWithinDelta);
    RUN_TEST(testHEX32sWithinDeltaAndCustomMessage);
    RUN_TEST(testHEX32sNotWithinDelta);
    RUN_TEST(testHEX32sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testHEX32sNotWithinDeltaEvenThoughASignedIntWouldPass);
    RUN_TEST(testHEX32sNotWithinDeltaEvenThoughASignedIntWouldPassAndCustomMessage);
    RUN_TEST(testHEX16sWithinDelta);
    RUN_TEST(testHEX16sWithinDeltaAndCustomMessage);
    RUN_TEST(testHEX16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits);
    RUN_TEST(testHEX16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage);
    RUN_TEST(testHEX16sNotWithinDelta);
    RUN_TEST(testHEX16sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testHEX8sWithinDelta);
    RUN_TEST(testHEX8sWithinDeltaAndCustomMessage);
    RUN_TEST(testHEX8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits);
    RUN_TEST(testHEX8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage);
    RUN_TEST(testHEX8sNotWithinDelta);
    RUN_TEST(testHEX8sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT32sWithinDelta);
    RUN_TEST(testUINT32sWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT32sNotWithinDelta);
    RUN_TEST(testUINT32sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT32sNotWithinDeltaEvenThoughASignedIntWouldPass);
    RUN_TEST(testUINT32sNotWithinDeltaEvenThoughASignedIntWouldPassAndCustomMessage);
    RUN_TEST(testUINT16sWithinDelta);
    RUN_TEST(testUINT16sWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits);
    RUN_TEST(testUINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage);
    RUN_TEST(testUINT16sNotWithinDelta);
    RUN_TEST(testUINT16sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT8sWithinDelta);
    RUN_TEST(testUINT8sWithinDeltaAndCustomMessage);
    RUN_TEST(testUINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits);
    RUN_TEST(testUINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage);
    RUN_TEST(testUINT8sNotWithinDelta);
    RUN_TEST(testUINT8sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testINT32sWithinDelta);
    RUN_TEST(testINT32sWithinDeltaAndCustomMessage);
    RUN_TEST(testINT32sNotWithinDelta);
    RUN_TEST(testINT32sNotWithinDeltaAndDifferenceOverflows);
    RUN_TEST(testINT32sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testINT16sWithinDelta);
    RUN_TEST(testINT16sWithinDeltaAndCustomMessage);
    RUN_TEST(testINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16Bits);
    RUN_TEST(testINT16sWithinDeltaWhenThereAreDifferenceOutsideOf16BitsAndCustomMessage);
    RUN_TEST(testINT16sNotWithinDelta);
    RUN_TEST(testINT16sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testINT8sWithinDelta);
    RUN_TEST(testINT8sWithinDeltaAndCustomMessage);
    RUN_TEST(testINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8Bits);
    RUN_TEST(testINT8sWithinDeltaWhenThereAreDifferenceOutsideOf8BitsAndCustomMessage);
    RUN_TEST(testINT8sNotWithinDelta);
    RUN_TEST(testINT8sNotWithinDeltaAndCustomMessage);
    RUN_TEST(testEqualStrings);
    RUN_TEST(testEqualStringsLen);
    RUN_TEST(testEqualStringsWithCarriageReturnsAndLineFeeds);
    RUN_TEST(testNotEqualString1);
    RUN_TEST(testNotEqualStringLen1);
    RUN_TEST(testNotEqualString2);
    RUN_TEST(testNotEqualStringLen2);
    RUN_TEST(testNotEqualString3);
    RUN_TEST(testNotEqualStringLen3);
    RUN_TEST(testNotEqualString4);
    RUN_TEST(testNotEqualStringLen4);
    RUN_TEST(testNotEqualString5);
    RUN_TEST(testNotEqualString_ExpectedStringIsNull);
    RUN_TEST(testNotEqualStringLen_ExpectedStringIsNull);
    RUN_TEST(testNotEqualString_ActualStringIsNull);
    RUN_TEST(testNotEqualStringLen_ActualStringIsNull);
    RUN_TEST(testEqualStringArrays);
    RUN_TEST(testNotEqualStringArray1);
    RUN_TEST(testNotEqualStringArray2);
    RUN_TEST(testNotEqualStringArray3);
    RUN_TEST(testNotEqualStringArray4);
    RUN_TEST(testNotEqualStringArray5);
    RUN_TEST(testNotEqualStringArray6);
    RUN_TEST(testEqualStringArrayIfBothNulls);
    RUN_TEST(testNotEqualStringArrayLengthZero);
    RUN_TEST(testEqualStringEachEqual);
    RUN_TEST(testNotEqualStringEachEqual1);
    RUN_TEST(testNotEqualStringEachEqual2);
    RUN_TEST(testNotEqualStringEachEqual3);
    RUN_TEST(testNotEqualStringEachEqual4);
    RUN_TEST(testNotEqualStringEachEqual5);
    RUN_TEST(testEqualMemory);
    RUN_TEST(testNotEqualMemory1);
    RUN_TEST(testNotEqualMemory2);
    RUN_TEST(testNotEqualMemory3);
    RUN_TEST(testNotEqualMemory4);
    RUN_TEST(testNotEqualMemoryLengthZero);
    RUN_TEST(testEqualIntArrays);
    RUN_TEST(testNotEqualIntArraysNullExpected);
    RUN_TEST(testNotEqualIntArraysNullActual);
    RUN_TEST(testNotEqualIntArrays1);
    RUN_TEST(testNotEqualIntArrays2);
    RUN_TEST(testNotEqualIntArrays3);
    RUN_TEST(testNotEqualIntArraysLengthZero);
    RUN_TEST(testEqualIntEachEqual);
    RUN_TEST(testNotEqualIntEachEqualNullActual);
    RUN_TEST(testNotEqualIntEachEqual1);
    RUN_TEST(testNotEqualIntEachEqual2);
    RUN_TEST(testNotEqualIntEachEqual3);
    RUN_TEST(testNotEqualEachEqualLengthZero);
    RUN_TEST(testEqualPtrArrays);
    RUN_TEST(testNotEqualPtrArraysNullExpected);
    RUN_TEST(testNotEqualPtrArraysNullActual);
    RUN_TEST(testNotEqualPtrArrays1);
    RUN_TEST(testNotEqualPtrArrays2);
    RUN_TEST(testNotEqualPtrArrays3);
    RUN_TEST(testEqualPtrEachEqual);
    RUN_TEST(testNotEqualPtrEachEqualNullExpected);
    RUN_TEST(testNotEqualPtrEachEqualNullActual);
    RUN_TEST(testNotEqualPtrEachEqual1);
    RUN_TEST(testNotEqualPtrEachEqual2);
    RUN_TEST(testNotEqualPtrEachEqual3);
    RUN_TEST(testEqualInt8Arrays);
    RUN_TEST(testNotEqualInt8Arrays);
    RUN_TEST(testEqualInt8EachEqual);
    RUN_TEST(testNotEqualInt8EachEqual);
    RUN_TEST(testEqualUIntArrays);
    RUN_TEST(testNotEqualUIntArrays1);
    RUN_TEST(testNotEqualUIntArrays2);
    RUN_TEST(testNotEqualUIntArrays3);
    RUN_TEST(testEqualUIntEachEqual);
    RUN_TEST(testNotEqualUIntEachEqual1);
    RUN_TEST(testNotEqualUIntEachEqual2);
    RUN_TEST(testNotEqualUIntEachEqual3);
    RUN_TEST(testEqualInt16Arrays);
    RUN_TEST(testNotEqualInt16Arrays);
    RUN_TEST(testEqualInt16EachEqual);
    RUN_TEST(testNotEqualInt16EachEqual);
    RUN_TEST(testEqualInt32Arrays);
    RUN_TEST(testNotEqualInt32Arrays);
    RUN_TEST(testEqualInt32EachEqual);
    RUN_TEST(testNotEqualInt32EachEqual);
    RUN_TEST(testEqualUINT8Arrays);
    RUN_TEST(testNotEqualUINT8Arrays1);
    RUN_TEST(testNotEqualUINT8Arrays2);
    RUN_TEST(testNotEqualUINT8Arrays3);
    RUN_TEST(testEqualUINT16Arrays);
    RUN_TEST(testNotEqualUINT16Arrays1);
    RUN_TEST(testNotEqualUINT16Arrays2);
    RUN_TEST(testNotEqualUINT16Arrays3);
    RUN_TEST(testEqualUINT32Arrays);
    RUN_TEST(testNotEqualUINT32Arrays1);
    RUN_TEST(testNotEqualUINT32Arrays2);
    RUN_TEST(testNotEqualUINT32Arrays3);
    RUN_TEST(testEqualHEXArrays);
    RUN_TEST(testNotEqualHEXArrays1);
    RUN_TEST(testNotEqualHEXArrays2);
    RUN_TEST(testNotEqualHEXArrays3);
    RUN_TEST(testEqualHEX32Arrays);
    RUN_TEST(testNotEqualHEX32Arrays1);
    RUN_TEST(testNotEqualHEX32Arrays2);
    RUN_TEST(testNotEqualHEX32Arrays3);
    RUN_TEST(testEqualHEX16Arrays);
    RUN_TEST(testNotEqualHEX16Arrays1);
    RUN_TEST(testNotEqualHEX16Arrays2);
    RUN_TEST(testNotEqualHEX16Arrays3);
    RUN_TEST(testEqualHEX8Arrays);
    RUN_TEST(testNotEqualHEX8Arrays1);
    RUN_TEST(testNotEqualHEX8Arrays2);
    RUN_TEST(testNotEqualHEX8Arrays3);
    RUN_TEST(testEqualUINT8EachEqual);
    RUN_TEST(testNotEqualUINT8EachEqual1);
    RUN_TEST(testNotEqualUINT8EachEqual2);
    RUN_TEST(testNotEqualUINT8EachEqual3);
    RUN_TEST(testEqualUINT16EachEqual);
    RUN_TEST(testNotEqualUINT16EachEqual1);
    RUN_TEST(testNotEqualUINT16EachEqual2);
    RUN_TEST(testNotEqualUINT16EachEqual3);
    RUN_TEST(testEqualUINT32EachEqual);
    RUN_TEST(testNotEqualUINT32EachEqual1);
    RUN_TEST(testNotEqualUINT32EachEqual2);
    RUN_TEST(testNotEqualUINT32EachEqual3);
    RUN_TEST(testEqualHEXEachEqual);
    RUN_TEST(testNotEqualHEXEachEqual1);
    RUN_TEST(testNotEqualHEXEachEqual2);
    RUN_TEST(testNotEqualHEXEachEqual3);
    RUN_TEST(testEqualHEX32EachEqual);
    RUN_TEST(testNotEqualHEX32EachEqual1);
    RUN_TEST(testNotEqualHEX32EachEqual2);
    RUN_TEST(testNotEqualHEX32EachEqual3);
    RUN_TEST(testEqualHEX16EachEqual);
    RUN_TEST(testNotEqualHEX16EachEqual1);
    RUN_TEST(testNotEqualHEX16EachEqual2);
    RUN_TEST(testNotEqualHEX16EachEqual3);
    RUN_TEST(testEqualHEX8EachEqual);
    RUN_TEST(testNotEqualHEX8EachEqual1);
    RUN_TEST(testNotEqualHEX8EachEqual2);
    RUN_TEST(testNotEqualHEX8EachEqual3);
    RUN_TEST(testEqualMemoryArrays);
    RUN_TEST(testNotEqualMemoryArraysExpectedNull);
    RUN_TEST(testNotEqualMemoryArraysActualNull);
    RUN_TEST(testNotEqualMemoryArrays1);
    RUN_TEST(testNotEqualMemoryArrays2);
    RUN_TEST(testNotEqualMemoryArrays3);
    RUN_TEST(testEqualMemoryEachEqual);
    RUN_TEST(testNotEqualMemoryEachEqualExpectedNull);
    RUN_TEST(testNotEqualMemoryEachEqualActualNull);
    RUN_TEST(testNotEqualMemoryEachEqual1);
    RUN_TEST(testNotEqualMemoryEachEqual2);
    RUN_TEST(testNotEqualMemoryEachEqual3);
    RUN_TEST(testProtection);
    RUN_TEST(testIgnoredAndThenFailInTearDown);
    RUN_TEST(testFailureCountIncrementsAndIsReturnedAtEnd);
    RUN_TEST(testCstringsEscapeSequence);
    RUN_TEST(testHexPrintsUpToMaxNumberOfNibbles);
    RUN_TEST(testPrintNumbers32);
    RUN_TEST(testPrintNumbersUnsigned32);
    RUN_TEST(testPrintNumbersInt64);
    RUN_TEST(testPrintNumbersUInt64);
    RUN_TEST(testEqualHex64s);
    RUN_TEST(testEqualUint64s);
    RUN_TEST(testEqualInt64s);
    RUN_TEST(testNotEqualHex64s);
    RUN_TEST(testNotEqualUint64s);
    RUN_TEST(testNotEqualInt64s);
    RUN_TEST(testNotEqualHex64sIfSigned);
    RUN_TEST(testHEX64sWithinDelta);
    RUN_TEST(testHEX64sNotWithinDelta);
    RUN_TEST(testHEX64sNotWithinDeltaEvenThoughASignedIntWouldPass);
    RUN_TEST(testUINT64sWithinDelta);
    RUN_TEST(testUINT64sNotWithinDelta);
    RUN_TEST(testUINT64sNotWithinDeltaEvenThoughASignedIntWouldPass);
    RUN_TEST(testINT64sWithinDelta);
    RUN_TEST(testINT64sNotWithinDelta);
    RUN_TEST(testINT64sNotWithinDeltaAndDifferenceOverflows);
    RUN_TEST(testEqualHEX64Arrays);
    RUN_TEST(testEqualUint64Arrays);
    RUN_TEST(testEqualInt64Arrays);
    RUN_TEST(testNotEqualHEX64Arrays1);
    RUN_TEST(testNotEqualHEX64Arrays2);
    RUN_TEST(testNotEqualUint64Arrays);
    RUN_TEST(testNotEqualInt64Arrays);
    RUN_TEST(testFloatsWithinDelta);
    RUN_TEST(testFloatsNotWithinDelta);
    RUN_TEST(testFloatsEqual);
    RUN_TEST(testFloatsNotEqual);
    RUN_TEST(testFloatsNotEqualNegative1);
    RUN_TEST(testFloatsNotEqualNegative2);
    RUN_TEST(testFloatsNotEqualActualNaN);
    RUN_TEST(testFloatsNotEqualExpectedNaN);
    RUN_TEST(testFloatsEqualBothNaN);
    RUN_TEST(testFloatsNotEqualInfNaN);
    RUN_TEST(testFloatsNotEqualNaNInf);
    RUN_TEST(testFloatsNotEqualActualInf);
    RUN_TEST(testFloatsNotEqualExpectedInf);
    RUN_TEST(testFloatsEqualBothInf);
    RUN_TEST(testFloatsNotEqualPlusMinusInf);
    RUN_TEST(testFloatIsPosInf1);
    RUN_TEST(testFloatIsPosInf2);
    RUN_TEST(testFloatIsNegInf1);
    RUN_TEST(testFloatIsNegInf2);
    RUN_TEST(testFloatIsNotPosInf1);
    RUN_TEST(testFloatIsNotPosInf2);
    RUN_TEST(testFloatIsNotNegInf);
    RUN_TEST(testFloatIsNan1);
    RUN_TEST(testFloatIsNan2);
    RUN_TEST(testFloatIsNotNan1);
    RUN_TEST(testFloatIsNotNan2);
    RUN_TEST(testFloatInfIsNotNan);
    RUN_TEST(testFloatNanIsNotInf);
    RUN_TEST(testFloatIsDeterminate1);
    RUN_TEST(testFloatIsDeterminate2);
    RUN_TEST(testFloatIsNotDeterminate1);
    RUN_TEST(testFloatIsNotDeterminate2);
    RUN_TEST(testFloatTraitFailsOnInvalidTrait);
    RUN_TEST(testEqualFloatArrays);
    RUN_TEST(testNotEqualFloatArraysExpectedNull);
    RUN_TEST(testNotEqualFloatArraysActualNull);
    RUN_TEST(testNotEqualFloatArrays1);
    RUN_TEST(testNotEqualFloatArrays2);
    RUN_TEST(testNotEqualFloatArrays3);
    RUN_TEST(testNotEqualFloatArraysNegative1);
    RUN_TEST(testNotEqualFloatArraysNegative2);
    RUN_TEST(testNotEqualFloatArraysNegative3);
    RUN_TEST(testEqualFloatArraysNaN);
    RUN_TEST(testEqualFloatArraysInf);
    RUN_TEST(testNotEqualFloatArraysLengthZero);
    RUN_TEST(testEqualFloatEachEqual);
    RUN_TEST(testNotEqualFloatEachEqualActualNull);
    RUN_TEST(testNotEqualFloatEachEqual1);
    RUN_TEST(testNotEqualFloatEachEqual2);
    RUN_TEST(testNotEqualFloatEachEqual3);
    RUN_TEST(testNotEqualFloatEachEqualNegative1);
    RUN_TEST(testNotEqualFloatEachEqualNegative2);
    RUN_TEST(testNotEqualFloatEachEqualNegative3);
    RUN_TEST(testEqualFloatEachEqualNaN);
    RUN_TEST(testEqualFloatEachEqualInf);
    RUN_TEST(testNotEqualFloatEachEqualLengthZero);
    RUN_TEST(testFloatPrinting);
    RUN_TEST(testFloatPrintingRoundTiesToEven);
    RUN_TEST(testFloatPrintingInfinityAndNaN);
    RUN_TEST(testAllFloatPrintingPart1_LessThan32Bits);
    RUN_TEST(testAllFloatPrintingPart2_Larger);
    RUN_TEST(testAllFloatPrintingPart3_LargerStill);
    RUN_TEST(testDoublesWithinDelta);
    RUN_TEST(testDoublesNotWithinDelta);
    RUN_TEST(testDoublesEqual);
    RUN_TEST(testDoublesNotEqual);
    RUN_TEST(testDoublesNotEqualNegative1);
    RUN_TEST(testDoublesNotEqualNegative2);
    RUN_TEST(testDoublesNotEqualActualNaN);
    RUN_TEST(testDoublesNotEqualExpectedNaN);
    RUN_TEST(testDoublesEqualBothNaN);
    RUN_TEST(testDoublesNotEqualInfNaN);
    RUN_TEST(testDoublesNotEqualNaNInf);
    RUN_TEST(testDoublesNotEqualActualInf);
    RUN_TEST(testDoublesNotEqualExpectedInf);
    RUN_TEST(testDoublesEqualBothInf);
    RUN_TEST(testDoublesNotEqualPlusMinusInf);
    RUN_TEST(testDoubleIsPosInf1);
    RUN_TEST(testDoubleIsPosInf2);
    RUN_TEST(testDoubleIsNegInf1);
    RUN_TEST(testDoubleIsNegInf2);
    RUN_TEST(testDoubleIsNotPosInf1);
    RUN_TEST(testDoubleIsNotPosInf2);
    RUN_TEST(testDoubleIsNotNegInf);
    RUN_TEST(testDoubleIsNan1);
    RUN_TEST(testDoubleIsNan2);
    RUN_TEST(testDoubleIsNotNan1);
    RUN_TEST(testDoubleIsNotNan2);
    RUN_TEST(testDoubleInfIsNotNan);
    RUN_TEST(testDoubleNanIsNotInf);
    RUN_TEST(testDoubleIsDeterminate1);
    RUN_TEST(testDoubleIsDeterminate2);
    RUN_TEST(testDoubleIsNotDeterminate1);
    RUN_TEST(testDoubleIsNotDeterminate2);
    RUN_TEST(testDoubleTraitFailsOnInvalidTrait);
    RUN_TEST(testEqualDoubleArrays);
    RUN_TEST(testNotEqualDoubleArraysExpectedNull);
    RUN_TEST(testNotEqualDoubleArraysActualNull);
    RUN_TEST(testNotEqualDoubleArrays1);
    RUN_TEST(testNotEqualDoubleArrays2);
    RUN_TEST(testNotEqualDoubleArrays3);
    RUN_TEST(testNotEqualDoubleArraysNegative1);
    RUN_TEST(testNotEqualDoubleArraysNegative2);
    RUN_TEST(testNotEqualDoubleArraysNegative3);
    RUN_TEST(testEqualDoubleArraysNaN);
    RUN_TEST(testEqualDoubleArraysInf);
    RUN_TEST(testNotEqualDoubleArraysLengthZero);
    RUN_TEST(testEqualDoubleEachEqual);
    RUN_TEST(testNotEqualDoubleEachEqualActualNull);
    RUN_TEST(testNotEqualDoubleEachEqual1);
    RUN_TEST(testNotEqualDoubleEachEqual2);
    RUN_TEST(testNotEqualDoubleEachEqual3);
    RUN_TEST(testNotEqualDoubleEachEqualNegative1);
    RUN_TEST(testNotEqualDoubleEachEqualNegative2);
    RUN_TEST(testNotEqualDoubleEachEqualNegative3);
    RUN_TEST(testEqualDoubleEachEqualNaN);
    RUN_TEST(testEqualDoubleEachEqualInf);
    RUN_TEST(testNotEqualDoubleEachEqualLengthZero);
    RUN_TEST(testDoublePrinting);
    RUN_TEST(testDoublePrintingRoundTiesToEven);
    RUN_TEST(testDoublePrintingInfinityAndNaN);
    RUN_TEST(testThatDetailsCanBeHandleOneDetail);
    RUN_TEST(testThatDetailsCanHandleTestFail);
    RUN_TEST(testThatDetailsCanBeHandleTwoDetails);
    RUN_TEST(testThatDetailsCanBeHandleSingleDetailClearingTwoDetails);

    return UNITY_END();
}
