#!/bin/sh /etc/rc.common

START=98

SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

board=$(board_name)

start() {
	. /lib/functions.sh

	local enabled

	config_load 'cooling'
	config_get_bool enabled config 'Enabled' '0'

	[ "$enabled" -gt 0 ] || return 1

	case "$board" in
	sonicfi,rap630c-311g|\
	sonicfi,rap630w-311g)
        service_start /usr/sbin/cooling
		;;
	esac

}

stop() {
	service_stop /usr/sbin/cooling
}
