#!/bin/sh

[ -d /etc/config-shadow/ ] && exit 0

hname=$(cat /sys/class/net/eth0/address | tr -d : | awk '{print tolower($0)}')
uci set system.@system[-1].hostname=$hname
uci set ucentral.config.serial=$hname
uci set network.wan6.ifname=@wan
uci set network.wan.type=bridge
uci commit

cp -r /etc/config/ /etc/config-shadow/

. /lib/functions.sh

UCI_CONFIG_DIR=/etc/config-shadow

iface_del() {
	uci -c $UCI_CONFIG_DIR delete wireless.$1
}

config_load wireless
config_foreach iface_del wifi-iface

uci -c $UCI_CONFIG_DIR commit
