#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/share/uspot/uspot.uc
DAS_PROG=/usr/bin/uspot-das

launch_das() {
	local uspot="$1"

	procd_open_instance "$uspot"
	procd_set_param command "$DAS_PROG" -u "$uspot"
	procd_set_param respawn
	procd_close_instance
}

add_das() {
	local cfg="$1"
	local das_secret

	config_get das_secret "$cfg" "das_secret" "0"
	[ "$das_secret" = "0" ] || launch_das "$cfg"
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance

	config_load uspot
	config_foreach add_das uspot
}
