#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/share/uspot/accounting.uc

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
