#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
sercomm,wallaby|\
wallys,dr6018|\
wallys,dr6018-v4|\
cig,wf188n|\
cig,wf194c|\
cig,wf194c4)
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth0" "tx rx link"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	;;
edgecore,eap101)
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	ucidef_set_led_netdev "lan1" "lan1" "green:lan1" "eth1"
	ucidef_set_led_netdev "lan2" "lan2" "green:lan2" "eth2"
	ucidef_set_led_netdev "poe" "poe" "green:wan" "eth0"
	;;
edgecore,eap102)
	ucidef_set_led_netdev "poe" "poe" "green:wan" "eth0"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	;;
edgecore,eap104)
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	ucidef_set_led_netdev "wan" "wan" "yellow:uplink" "eth0"
	;;
liteon,wpx8324)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "orange:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	ucidef_set_led_netdev "wan" "wan" "blue:uplink" "eth0"
	;;
hfcl,ion4xi|\
hfcl,ion4x|\
hfcl,ion4x_2|\
hfcl,ion4xe)
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "blue:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "blue:wifi2" "phy1tpt"
	;;
glinet,ax1800|\
glinet,axt1800)
	ucidef_set_led_netdev "wan" "WAN" "blue:wan" "eth0" "tx rx link"
	;;
yuncore,fap650|\
muxi,ap3220l)
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	;;
esac

board_config_flush

exit 0
