#!/bin/sh /etc/rc.common

START=99

boot() {
	case $(board_name) in
	edgecore,eap115|\
	edgecore,eap115a)
		# Only set for 2.4G, trigger temp 105, restore temp 95
		echo 95000 > /sys/class/hwmon/hwmon1/temp1_crit
		echo 105000 > /sys/class/hwmon/hwmon1/temp1_max
		;;
	esac
}
