#!/bin/sh

. /usr/share/libubox/jshn.sh
[ "$ACTION" = "add" ] || exit 0

json_init
json_load "$(cat /etc/board.json)"
json_select network
	json_select "wan"
		json_get_vars ifname
	json_select ..
json_select ..

[ -n "$ifname" ] || {
	ifname=$(uci get network.wan.ifname)
	ifname=${ifname%% *}
}

net=$(uci get wireless.${DEVICENAME}.network)
vid=$(uci get wireless.${DEVICENAME}.vid)

[ -z "$net" -o -z "$vid" -o "$vid" = 0 ] && exit 0

bridge vlan add vid $vid dev br-lan self
bridge vlan add vid $vid dev br-wan self
bridge vlan add vid $vid dev $ifname
bridge vlan add pvid $vid vid $vid dev ${DEVICENAME} untagged
exit 0
