#!/bin/sh

[ "$ACTION" = "add" ] || exit 0
phy=$(cat /sys/class/net/${DEVICENAME}/phy80211/name)

rlimit=$(uci get wireless.${DEVICENAME}.rlimit)

[ -z "$rlimit" -o -z "$phy" ] && exit 0
/etc/init.d/nft-qos restart
exit 0
