#!/bin/sh

[ "$ACTION" = "add" ] || exit 0

logger -t "hotplug" $DEVICENAME

rlimit=$(uci get wireless.${DEVICENAME}.rlimit)

[ -z "$rlimit" -o "$rlimit" = 0 ] && exit 0
/etc/init.d/nft-qos restart
exit 0
