#!/bin/sh
. /usr/share/libubox/jshn.sh
[ "$ACTION" = "add" ] || exit 0

json_init
json_load "$(cat /etc/board.json)"
json_select network
	json_select "wan"
		json_get_vars ifname
	json_select ..
json_select ..

[ -n "$ifname" ] || {
	ifname=$(uci get network.wan.ifname)
	ifname=${ifname%% *}
}

dvid=`echo $DEVICENAME | awk -F "." '{ printf $2 }'`
[ -z "$dvid" -o "$dvid" = 0 -o "$dvid" = 1 ] && exit 0

iface=`echo $DEVICENAME | awk -F "." '{ printf $1 }'`
iswlan=`echo $iface | grep -ic wlan`
[ "$iswlan" = 0 ] && exit 0

logger -t "Add Dynamic VLAN" "dev" "$DEVICENAME" "dvid=" "$dvid"

brctl delif br-wan.$dvid $DEVICENAME
brctl addif br-wan $DEVICENAME

bridge vlan add vid $dvid dev br-wan self
bridge vlan add vid $dvid dev $ifname
bridge vlan add pvid $dvid vid $dvid dev $DEVICENAME untagged
bridge vlan add vid $dvid dev br-lan self

exit 0
