#!/bin/sh

[ "${ACTION}" = "add" ] || exit 0

phy=$(cat /sys/class/net/${DEVICENAME}/phy80211/name)
radio=$(uci get wireless.${DEVICENAME}.device)
hwmode=$(uci get wireless.${radio}.hwmode)

[ -z "$phy" -o -z "$radio" -o -z "$hwmode" ] && exit 0

[ "${hwmode}" = "11a" ] && band=5 || band=2

bcn_rate=$(($(uci get wireless.${DEVICENAME}.bcn_rate)/10))
mcast_rate=$(uci get wireless.${DEVICENAME}.mcast_rate)

ATH10K_FILE="/sys/kernel/debug/ieee80211/${phy}/ath10k/set_rates"
if [ -f "$ATH10K_FILE" ]; then
# ath10k rate-codes: 0x43 1M, 0x42 2M, 0x41 5.5M, 0x40 11M, 0x3 6M, 0x7 9M, 0x2 12M, 0x6 18M, 0x1 24M, 0x5 36M, 0x0 48M, 0x4 54M, 0xFF default

	rate_codes="1:0x43 2:0x42 5:0x41 11:0x40 6:0x3 9:0x7 12:0x2 18:0x6 24:0x1 36:0x5 48:0x0 54:0x4"
	SET_RATES_PATH=${ATH10K_FILE}
fi

ATH11K_FILE="/sys/kernel/debug/ieee80211/${phy}/ath11k/set_rates"
if [ -f "$ATH11K_FILE" ]; then
# ath11k rate-codes: 0x10000103 1M, 0x10000102 2M, 0x10000101 5.5M, 0x10000100 11M, 0x10000003 6M, 0x10000007 9M, 0x10000002 12M, 0x10000006 18M, 0x10000001 24M, 0x10000005 36M, 0x10000000 48M, 0x10000004 54M

	rate_codes="1:0x10000103 2:0x10000102 5:0x10000101 11:0x10000100 6:0x10000003 9:0x10000007 12:0x10000002 18:0x10000006 24:0x10000001 36:0x10000005 48:0x10000000 54:0x10000004"
	SET_RATES_PATH=${ATH11K_FILE}
fi

# Default codes
beacon_code=0xFF
mcast_code=0xFF

for rate_code in $rate_codes ; do
        rate="${rate_code%%:*}"
        code="${rate_code##*:}"
        if [ "${rate_code%%:*}" == "$bcn_rate" ] ; then
                beacon_code="${rate_code##*:}"
        fi
        if [ "${rate_code%%:*}" == "$mcast_rate" ] ; then
                mcast_code="${rate_code##*:}"
        fi
done

# set rates
logger -t hotplug "Set Tx rates for device ${DEVICENAME}"
sleep 20

[ "${beacon_code}" = "0xFF" ] || {
	echo "${DEVICENAME} beacon ${band} ${beacon_code}" > ${SET_RATES_PATH}

	if [ -f "$ATH11K_FILE" ]; then
		echo "${DEVICENAME} mgmt ${band} ${beacon_code}" > ${SET_RATES_PATH}
	fi
}

[ "${mcast_code}" = "0xFF" ] || {
	echo "${DEVICENAME} mcast ${band} ${mcast_code}" > ${SET_RATES_PATH}
}
