#!/bin/sh /etc/rc.common
START=99

start() {
	#config watchdog to be kicked per second
	#ubus call system watchdog '{"frequency":1}'
	#reset bootting counter in hw info to indicate booting succesfully	
	rtk_bootinfo update

	echo 4096 > /proc/sys/vm/min_free_kbytes

	#mount yaffs on mtdblock1 for nand
	if [ -f "/proc/nandinfo" ]; then
		mkdir /hw_setting
		mount -t yaffs2 -o tags-ecc-off -o inband-tags /dev/mtdblock1 /hw_setting
	fi	
	#BT networking fine-tune from turnkey SDK
	#echo "24576" > /proc/sys/net/ipv4/route/max_size
	echo "16384" > /proc/sys/net/ipv4/route/max_size
	echo "180" > /proc/sys/net/ipv4/route/gc_thresh
	echo 20 > /proc/sys/net/ipv4/route/gc_elasticity
	#echo "12288" > /proc/sys/net/netfilter/nf_conntrack_max
	echo "8192" > /proc/sys/net/netfilter/nf_conntrack_max
	echo "32" > /proc/sys/net/netfilter/nf_conntrack_expect_max

}


