#!/usr/bin/env python3
"""
Step 6: Publish generated files to specs/datamodel/.

Verifies all expected files exist in ``local/datamodel/``, then copies them
to ``specs/datamodel/`` and generates a ``MANIFEST.md`` with metadata.

Output:
    specs/datamodel/  (all generated files)
    specs/datamodel/MANIFEST.md
"""

import os
import shutil
import sys
from datetime import datetime, timezone

from config import (
    LOCAL_DATAMODEL_DIR, SPECS_DATAMODEL_DIR, ensure_output_dir,
    get_version_string,
)

# Files that must exist before publishing (produced by steps 1-5)
REQUIRED_FILES = [
    'tr181_definition.xlsx',
    'gw3_current_datamodel.xml',
    'gw3_current_datamodel.xlsx',
]

# Optional files that are copied if present
OPTIONAL_FILES = [
    'tr181_original.json',
    'gw3_current_datamodel.json',
]

FILE_DESCRIPTIONS = {
    'tr181_definition.xlsx': 'TR-181 data model standard definition (Excel)',
    'gw3_current_datamodel.xml': 'GW3 enhanced data model with coverage annotations (XML)',
    'gw3_current_datamodel.xlsx': 'GW3 enhanced data model with coverage report (Excel)',
    'gw3_current_datamodel.json': 'GW3 enhanced data model (JSON)',
    'tr181_original.json': 'TR-181 original data model (JSON)',
    'MANIFEST.md': 'This file — generation metadata and file index',
}


def detect_tr181_version():
    """Detect the TR-181 version from downloaded XML filenames."""
    if not os.path.isdir(LOCAL_DATAMODEL_DIR):
        return 'unknown'
    for fname in sorted(os.listdir(LOCAL_DATAMODEL_DIR), reverse=True):
        if fname.startswith('tr-181-') and fname.endswith('-usp-full.xml'):
            return get_version_string(fname)
    return 'unknown'


def check_required_files():
    """Verify all required files exist. Return list of missing files."""
    missing = []
    for fname in REQUIRED_FILES:
        path = os.path.join(LOCAL_DATAMODEL_DIR, fname)
        if not os.path.exists(path):
            missing.append(fname)
    return missing


def generate_manifest(dest_dir, version, files_copied):
    """Generate MANIFEST.md in the destination directory."""
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')

    lines = [
        '# GW3 Data Model Report',
        '',
        f'**Generated:** {now}',
        f'**TR-181 Version:** {version}',
        f'**Tool:** gw3-datamodel-report skill (Claude Code)',
        '',
        '## Files',
        '',
        '| File | Description |',
        '|------|-------------|',
    ]
    for fname in sorted(files_copied):
        desc = FILE_DESCRIPTIONS.get(fname, '')
        size = os.path.getsize(os.path.join(dest_dir, fname))
        size_str = f'{size / 1024:.0f} KB' if size > 1024 else f'{size} B'
        lines.append(f'| {fname} | {desc} ({size_str}) |')

    lines.append('')
    lines.append('## Pipeline')
    lines.append('')
    lines.append('Generated by `.github/skills/gw3-datamodel-report/` using steps 1-5.')
    lines.append('See `SKILL.md` for full pipeline documentation.')
    lines.append('')

    manifest_path = os.path.join(dest_dir, 'MANIFEST.md')
    with open(manifest_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    return manifest_path


def main():
    print("=== Step 6: Publish to specs/datamodel/ ===")

    # Check prerequisites
    missing = check_required_files()
    if missing:
        print(f"ERROR: Missing required files in {LOCAL_DATAMODEL_DIR}:", file=sys.stderr)
        for f in missing:
            print(f"  - {f}", file=sys.stderr)
        print("Run steps 1-5 first.", file=sys.stderr)
        sys.exit(1)

    version = detect_tr181_version()
    print(f"TR-181 version: {version}")

    # Prepare destination
    ensure_output_dir(SPECS_DATAMODEL_DIR)

    # Clear old files (but not .gitkeep or other non-generated files)
    for fname in os.listdir(SPECS_DATAMODEL_DIR):
        fpath = os.path.join(SPECS_DATAMODEL_DIR, fname)
        if os.path.isfile(fpath) and not fname.startswith('.'):
            os.remove(fpath)

    # Copy files
    files_copied = []
    for fname in REQUIRED_FILES + OPTIONAL_FILES:
        src = os.path.join(LOCAL_DATAMODEL_DIR, fname)
        if os.path.exists(src):
            dst = os.path.join(SPECS_DATAMODEL_DIR, fname)
            shutil.copy2(src, dst)
            files_copied.append(fname)
            size = os.path.getsize(dst)
            print(f"  Copied: {fname} ({size / 1024:.0f} KB)")

    # Also copy any XML files that match tr-181-*
    for fname in sorted(os.listdir(LOCAL_DATAMODEL_DIR)):
        if fname.startswith('tr-181-') and fname.endswith('.xml'):
            src = os.path.join(LOCAL_DATAMODEL_DIR, fname)
            dst = os.path.join(SPECS_DATAMODEL_DIR, fname)
            if not os.path.exists(dst):
                shutil.copy2(src, dst)
                files_copied.append(fname)
                print(f"  Copied: {fname}")

    # Generate manifest
    manifest = generate_manifest(SPECS_DATAMODEL_DIR, version, files_copied)
    files_copied.append('MANIFEST.md')
    print(f"  Generated: MANIFEST.md")

    print(f"\n=== Published {len(files_copied)} files to {SPECS_DATAMODEL_DIR}/ ===")

    return files_copied


if __name__ == '__main__':
    main()
