#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/rrmd.uc
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger rrm
}

reload_service() {
	ubus call rrm reload
}
