#!/bin/sh

[ "${ACTION}" = "add" ] && {
	basename "$(readlink -f "/sys/${DEVPATH}/device/driver")" | grep '^morse_' || return;

	board_type=$(printf "%04x" "$(cat /sys/${DEVPATH}/device/board_type)");

	# Avoid mutating model information when OTP is not burnt, ie 0000.
	[ "$board_type" = "0000" ] && return;

	module_id=$(awk -F, '$1==b{print toupper($2)}' b="$board_type" /usr/share/morse-bcf/db.txt)

	model=$(cat /tmp/sysinfo/model)

	# Don't append a module id if that module id already exists in the model
	[ "${model%-"$module_id"}" != "${model}" ] && return;

	echo "$model-$module_id" > /tmp/sysinfo/model
}
