#!/bin/sh /etc/rc.common

START=99

boot() {
	case "$(board_name)" in
	edgecore,eap105)
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] && fw_setenv upgrade_available 1
		fw_setenv bootcount 0
		;;
	esac
}
