#!/bin/sh

. /lib/functions/uci-defaults.sh
. /lib/realtek.sh

board=$(realtek_board_name)

board_config_update

case $board in
	sp-w2m-ac1200)
        	ucidef_set_led_netdev "wifi2" "wifi2" "led1" "wlan1"
        	ucidef_set_led_netdev "wifi5" "wifi5" "led2" "wlan0"
        	ucidef_set_led_netdev "wan" "WAN" "led3" "eth0"
        	ucidef_set_led_netdev "lan" "LAN" "led4" "eth1"

		;;
esac

board_config_flush

exit 0
