#!/bin/sh

. /lib/functions.sh
. /lib/realtek.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

realtek_setup_interfaces()
{
	local board="$1"

	case $board in
	sp-w2m-ac1200)
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		;;

	esac
}

board_config_update
board=$(realtek_board_name)
realtek_setup_interfaces $board
board_config_flush

exit 0
