#!/bin/sh /etc/rc.common

START=80

boot() {
	DESC=$(cat /etc/openwrt_release | grep DISTRIB_DESCRIPTION= | cut -d\' -f2)
	HASH=$(cat /etc/openwrt_release | grep DISTRIB_TIP= | cut -d\' -f2)
	VERSION=$(cat /etc/openwrt_release | grep DISTRIB_TIP_VERSION= | cut -d\' -f2)
	echo "$DESC / TIP-$VERSION-$HASH" > /tmp/ucentral.version
}
