#!/bin/sh /etc/rc.common

START=80

boot() {
	HASH=$(cat /etc/openwrt_release | grep DISTRIB_TIP= | cut -d\' -f2)
	VERSION=$(cat /etc/openwrt_release | grep DISTRIB_TIP_VERSION= | cut -d\' -f2)
	echo "$VERSION-$HASH" > /tmp/ucentral.version
}
