/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018,2020 The Linux Foundation. All rights reserved.
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _DT_BINDINGS_CLOCK_IPQ_GCC_DEVSOC_H
#define _DT_BINDINGS_CLOCK_IPQ_GCC_DEVSOC_H

#define GPLL0_MAIN				0
#define GPLL0					1
#define GPLL4_MAIN				2
#define GPLL4					3
#define GPLL2_MAIN				4
#define GPLL2					5
#define GCC_SLEEP_CLK_SRC			6
#define GCC_APSS_AHB_CLK_SRC			7
#define GCC_APSS_AXI_CLK_SRC			8
#define GCC_APSS_AHB_CLK			9
#define GCC_APSS_AXI_CLK			10
#define GCC_CPUSS_TRIG_CLK			11
#define GCC_GEMNOC_AHB_CLK			12
#define GCC_GEMNOC_ANOC_CLK			13
#define GCC_GEMNOC_APSS_CLK			14
#define GCC_GEMNOC_CNOC_CLK			15
#define GCC_GEMNOC_NSSNOC_CLK			16
#define GCC_GEMNOC_Q6_AXI_CLK			17
#define GCC_GEMNOC_QOSGEN_EXTREF_CLK		18
#define GCC_GEMNOC_SNOC_CLK			19
#define GCC_GEMNOC_TS_CLK			20
#define GCC_GEMNOC_XO_DBG_CLK			21
#define GCC_LLCC_TPDM_CFG_CLK			22
#define GCC_DEBUG_CLK				23
#define GCC_USB0_EUD_AT_CLK			24
#define GCC_PCIE0_AXI_M_CLK_SRC			25
#define GCC_PCIE0_AXI_M_CLK			26
#define GCC_PCIE1_AXI_M_CLK_SRC			27
#define GCC_PCIE1_AXI_M_CLK			28
#define GCC_PCIE2_AXI_M_CLK_SRC			29
#define GCC_PCIE2_AXI_M_CLK			30
#define GCC_PCIE3_AXI_M_CLK_SRC			31
#define GCC_PCIE3_AXI_M_CLK			32
#define GCC_PCIE0_AXI_S_CLK_SRC			33
#define GCC_PCIE0_AXI_S_BRIDGE_CLK		34
#define GCC_PCIE0_AXI_S_CLK			35
#define GCC_PCIE1_AXI_S_CLK_SRC			36
#define GCC_PCIE1_AXI_S_BRIDGE_CLK		37
#define GCC_PCIE1_AXI_S_CLK			38
#define GCC_PCIE2_AXI_S_CLK_SRC			39
#define GCC_PCIE2_AXI_S_BRIDGE_CLK		40
#define GCC_PCIE2_AXI_S_CLK			41
#define GCC_PCIE3_AXI_S_CLK_SRC			42
#define GCC_PCIE3_AXI_S_BRIDGE_CLK		43
#define GCC_PCIE3_AXI_S_CLK			44
#define GCC_PCIE0_PIPE_CLK_SRC			45
#define GCC_PCIE0_PIPE_CLK			46
#define GCC_PCIE1_PIPE_CLK_SRC			47
#define GCC_PCIE1_PIPE_CLK			48
#define GCC_PCIE2_PIPE_CLK_SRC			49
#define GCC_PCIE2_PIPE_CLK			50
#define GCC_PCIE3_PIPE_CLK_SRC			51
#define GCC_PCIE3_PIPE_CLK			52
#define GCC_PCIE_AUX_CLK_SRC			53
#define GCC_PCIE0_AUX_CLK			54
#define GCC_PCIE1_AUX_CLK			55
#define GCC_PCIE2_AUX_CLK			56
#define GCC_PCIE3_AUX_CLK			57
#define GCC_PCIE0_RCHNG_CLK_SRC			58
#define GCC_PCIE0_RCHNG_CLK			59
#define GCC_PCIE1_RCHNG_CLK_SRC			60
#define GCC_PCIE1_RCHNG_CLK			61
#define GCC_PCIE2_RCHNG_CLK_SRC			62
#define GCC_PCIE2_RCHNG_CLK			63
#define GCC_PCIE3_RCHNG_CLK_SRC			64
#define GCC_PCIE3_RCHNG_CLK			65
#define GCC_PCIE0_AHB_CLK			66
#define GCC_PCIE1_AHB_CLK			67
#define GCC_PCIE2_AHB_CLK			68
#define GCC_PCIE3_AHB_CLK			69
#define GCC_USB0_AUX_CLK_SRC			70
#define GCC_USB0_AUX_CLK			71
#define GCC_USB0_MASTER_CLK_SRC			72
#define GCC_USB0_MASTER_CLK			73
#define GCC_USB0_MOCK_UTMI_CLK_SRC		74
#define GCC_USB0_MOCK_UTMI_DIV_CLK_SRC		75
#define GCC_USB0_MOCK_UTMI_CLK			76
#define GCC_USB0_PIPE_CLK_SRC			77
#define GCC_USB0_PIPE_CLK			78
#define GCC_USB0_PHY_CFG_AHB_CLK		79
#define GCC_USB0_SLEEP_CLK			80
#define GCC_SDCC1_APPS_CLK_SRC			81
#define GCC_SDCC1_APPS_CLK			82
#define GCC_SDCC1_ICE_CORE_CLK_SRC		83
#define GCC_SDCC1_ICE_CORE_CLK			84
#define GCC_SDCC1_AHB_CLK			85
#define GCC_PCNOC_BFDCD_CLK_SRC			86
#define GCC_NSSCFG_CLK				87
#define GCC_NSSNOC_NSSCC_CLK			88
#define GCC_NSSCC_CLK				89
#define GCC_NSSNOC_PCNOC_1_CLK			90
#define GCC_QDSS_DAP_AHB_CLK			91
#define GCC_QDSS_CFG_AHB_CLK			92
#define GCC_SNOC_PCNOC_AHB_CLK			93
#define GCC_ANOC_PCNOC_AHB_CLK			94
#define GCC_QDSS_USB_CLK			95
#define GCC_QPIC_AHB_CLK			96
#define GCC_QPIC_CLK				97
#define GCC_Q6_AXIS_CLK				98
#define GCC_MDIO_AHB_CLK			99
#define GCC_MPM_AHB_CLK				100
#define GCC_PRNG_AHB_CLK			101
#define GCC_UNIPHY0_AHB_CLK			102
#define GCC_UNIPHY1_AHB_CLK			103
#define GCC_UNIPHY2_AHB_CLK			104
#define GCC_CMN_12GPLL_AHB_CLK			105
#define GCC_CMN_12GPLL_APU_CLK			106
#define GCC_SYSTEM_NOC_BFDCD_CLK_SRC		107
#define GCC_NSSNOC_SNOC_CLK			108
#define GCC_NSSNOC_SNOC_1_CLK			109
#define GCC_QDSS_ETR_USB_CLK			110
#define GCC_SYS_NOC_AXI_CLK			111
#define GCC_ANOC0_AXI_CLK			112
#define GCC_IMEM_AXI_CLK			113
#define GCC_WCSS_AHB_CLK_SRC			114
#define GCC_WCSS_AXI_M_CLK_SRC			120
#define GCC_QDSS_AT_CLK_SRC			122
#define GCC_NSSNOC_ATB_CLK			126
#define GCC_QDSS_AT_CLK				127
#define GCC_SYS_NOC_AT_CLK			128
#define GCC_PCNOC_AT_CLK			129
#define GCC_QDSS_EUD_AT_CLK			130
#define GCC_QDSS_STM_CLK_SRC			131
#define GCC_QDSS_STM_CLK			132
#define GCC_QDSS_TRACECLKIN_CLK_SRC		133
#define GCC_QDSS_TRACECLKIN_CLK			134
#define GCC_QDSS_TSCTR_CLK_SRC			135
#define GCC_QDSS_TSCTR_DIV2_CLK			139
#define GCC_QDSS_TS_CLK				140
#define GCC_SNOC_TS_CLK				141
#define GCC_QDSS_TSCTR_DIV4_CLK			142
#define GCC_NSS_TS_CLK				143
#define GCC_QDSS_TSCTR_DIV8_CLK			144
#define GCC_PCNOC_TS_CLK			145
#define GCC_QDSS_TSCTR_DIV16_CLK		146
#define GCC_QDSS_DAP_CLK			153
#define GCC_QDSS_APB2JTAG_CLK			154
#define GCC_QDSS_TSCTR_DIV3_CLK			155
#define GCC_QPIC_IO_MACRO_CLK_SRC		156
#define GCC_QPIC_IO_MACRO_CLK			157
#define GCC_Q6_AXI_CLK_SRC			158
#define GCC_NSSNOC_MEMNOC_BFDCD_CLK_SRC		160
#define GCC_NSSNOC_MEMNOC_CLK			161
#define GCC_NSSNOC_MEM_NOC_1_CLK		162
#define GCC_LPASS_AXIM_CLK_SRC			163
#define GCC_LPASS_CORE_AXIM_CLK			164
#define GCC_PCNOC_LPASS_CLK			165
#define GCC_LPASS_SWAY_CLK_SRC			166
#define GCC_LPASS_SWAY_CLK			167
#define GCC_SNOC_LPASS_CFG_CLK			168
#define GCC_ADSS_PWM_CLK_SRC			169
#define GCC_ADSS_PWM_CLK			170
#define GCC_AGGRNOC_ATB_CLK			171
#define GP1_CLK_SRC				172
#define GP2_CLK_SRC				173
#define GP3_CLK_SRC				174
#define GCC_GP1_CLK				175
#define GCC_GP2_CLK				176
#define GCC_GP3_CLK				177
#define GCC_DDRSS_SMS_SLOW_CLK_SRC		178
#define GCC_DDRSS_SMS_SLOW_CLK			179
#define GCC_XO_CLK_SRC				180
#define GCC_NSSNOC_XO_DCD_CLK			181
#define GCC_XO_CLK				182
#define GCC_NSSNOC_QOSGEN_REF_CLK		183
#define GCC_NSSNOC_TIMEOUT_REF_CLK		184
#define GCC_XO_DIV4_CLK				185
#define GCC_SPDM_FF_CLK				186
#define GCC_UNIPHY0_SYS_CLK			187
#define GCC_UNIPHY1_SYS_CLK			188
#define GCC_UNIPHY2_SYS_CLK			189
#define GCC_CMN_12GPLL_SYS_CLK			190
#define GCC_UNIPHY_SYS_CLK_SRC			192
#define GCC_NSS_TS_CLK_SRC			193
#define GCC_ANOC_PCIE0_1LANE_M_CLK		194
#define GCC_ANOC_PCIE1_1LANE_M_CLK		195
#define GCC_ANOC_PCIE2_2LANE_M_CLK		196
#define GCC_ANOC_PCIE3_2LANE_M_CLK		197
#define GCC_CNOC_PCIE0_1LANE_S_CLK		198
#define GCC_CNOC_PCIE1_1LANE_S_CLK		199
#define GCC_CNOC_PCIE2_2LANE_S_CLK		200
#define GCC_CNOC_PCIE3_2LANE_S_CLK		201
#define GCC_CNOC_APSS_AHB_CLK			202
#define GCC_CNOC_QDSS_STM_AXI_CLK		203
#define GCC_CNOC_QOSGEN_EXTREF_CLK		204
#define GCC_CNOC_TME_CFG_CLK			205
#define GCC_CNOC_USB_CLK			206
#define GCC_CNOC_WCSS_AHB_CLK			207
#define GCC_QX_CLK				208
#define GCC_QUPV3_2X_CORE_CLK			209
#define GCC_QUPV3_AHB_MST_CLK			210
#define GCC_QUPV3_AHB_SLV_CLK			211
#define GCC_QUPV3_CORE_CLK			212
#define GCC_QUPV3_SLEEP_CLK			213
#define GCC_QUPV3_I2C0_CLK			214
#define GCC_QUPV3_I2C1_CLK			215
#define GCC_QUPV3_SPI0_CLK			216
#define GCC_QUPV3_SPI1_CLK			217
#define GCC_QUPV3_UART0_CLK			218
#define GCC_QUPV3_UART1_CLK			219
#define GCC_RBCPR_AHB_CLK			220
#define GCC_RBCPR_CLK				221
#define GCC_PCNOC_WAPSS_CLK			222
#define GCC_SNOC_WAPSS_CLK			223
#define GCC_PCNOC_DIV4_CLK_SRC			224
#define GCC_QDSS_DAP_DIV6_CLK_SRC		225
#define GCC_ANOC0_AXI_CLK_SRC			226
#define GCC_QX_CLK_SRC				227
#define GCC_QPIC_CLK_SRC			228
#define GCC_QUPV3_2X_CORE_CLK_SRC		229
#define GCC_QUPV3_I2C0_CLK_SRC			230
#define GCC_QUPV3_I2C1_CLK_SRC			231
#define GCC_QUPV3_SPI0_CLK_SRC			232
#define GCC_QUPV3_SPI1_CLK_SRC			233
#define GCC_QUPV3_UART0_CLK_SRC			234
#define GCC_QUPV3_UART1_CLK_SRC			235
#define GCC_RBCPR_CLK_SRC			236
#define GCC_ACC_CLK_SRC				237
#define GCC_SEC_CTRL_CLK_SRC			238
/* Add new clocks on top of q6 bring up clocks
 * and update MAX_GCC_CLOCKS macro
 */
#define MAX_GCC_CLOCKS				238
#if defined(CONFIG_QCOM_NON_SECURE_PIL) || defined(__QCOM_NON_SECURE_PIL__)
#define GCC_Q6_TSCTR_1TO2_CLK			(MAX_GCC_CLOCKS + 1)
#define GCC_Q6SS_TRIG_CLK			(MAX_GCC_CLOCKS + 2)
#define GCC_Q6_AHB_S_CLK			(MAX_GCC_CLOCKS + 3)
#define GCC_Q6_AHB_CLK				(MAX_GCC_CLOCKS + 4)
#define GCC_Q6SS_ATBM_CLK			(MAX_GCC_CLOCKS + 5)
#define GCC_Q6_AXIM_CLK				(MAX_GCC_CLOCKS + 6)
#define	GCC_Q6SS_BOOT_CLK			(MAX_GCC_CLOCKS + 7)
#define GCC_WCSS_ECAHB_CLK			(MAX_GCC_CLOCKS + 8)
#define GCC_Q6SS_PCLKDBG_CLK			(MAX_GCC_CLOCKS + 9)
#endif

#endif
