#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1
PROG=/usr/bin/cloud_discovery

service_triggers() {
	procd_add_reload_trigger ucentral
}

reload_service() {
	ubus call cloud reload
}

start_service() {
	[ -f /etc/ucentral/capabilities.json ] || {
		mkdir -p /etc/ucentral/
		/usr/share/ucentral/capabilities.uc
	}

	local valid=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["valid"]')
	[ "$valid" == "true" ] || 
		/usr/share/ucentral/ucentral.uc /etc/ucentral/ucentral.cfg.0000000001 > /dev/null

	est_client check
	[ $? -eq 1 ] && {
		logger ERROR
		logger ERROR
		logger ERROR
		logger The certificate used has a CN that does not match the serial of the device
		echo The certificate used has a CN that does not match the serial of the device
		logger ERROR
		logger ERROR
		logger ERROR
		return
	}

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
