#!/bin/sh /etc/rc.common

START=90
STOP=01

boot() {
    mkdir -p /tmp/cpm/ || { logger -t init "Failed to create /tmp/cpm"; exit 1; }
    opkg list-installed > /tmp/packages.state || { logger -t init "Failed to list packages"; exit 1; }
    if [ -x /usr/share/ucentral/package_list.uc ]; then
        /usr/share/ucentral/package_list.uc || { logger -t init "Failed to execute package_list.uc"; exit 1; }
    else
        logger -t init "package_list.uc not found or not executable"
    fi
}
