#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/usr/sbin/ucentral

service_triggers() {
	procd_add_reload_trigger ucentral
}

start_service() {
	[ -f /etc/ucentral/capabilities.json ] || {
		ucode -m ubus -E board=/etc/board.json /usr/share/ucentral/capabilities.uc > /etc/ucentral/capabilities.json 
	}

	. /lib/functions.sh
	cp /etc/config-shadow/ucentral /etc/config/
	config_load 'ucentral'
	config_get serial 'config' 'serial'
	config_get server 'config' 'server'
	config_get port 'config' 'port'
	config_get debug 'config' 'debug' 0
	config_get insecure 'config' 'insecure' 0

	procd_open_instance
	procd_set_param command "$PROG"
	[ -n "$serial" ] && procd_append_param command -S $serial
	[ -n "$server" ] && procd_append_param command -s $server
	[ -n "$port" ] && procd_append_param command -P $port
	[ -n "$reporting" ] && procd_append_param command -r $reporting
	[ "$debug" -eq 0 ] || procd_append_param command -d
	[ "$insecure" -eq 0 ] || procd_append_param command -i
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

boot() {
	ucode -m fs -i /usr/share/ucentral/crashlog.uc
	start
}
