#!/bin/sh /etc/rc.common

START=99
STOP=01
USE_PROCD=1
PROG=/usr/sbin/ucentral

service_triggers() {
	procd_add_reload_trigger ucentral
}

reload_service() {
	restart
}

start_service() {
	[ -s /etc/ucentral/capabilities.json ] || rm /etc/ucentral/capabilities.json
	[ -f /etc/ucentral/capabilities.json ] || /usr/share/ucentral/capabilities.uc

	[ -f /etc/ucentral/ucentral.cfg.0000000002 ] && {
		/usr/share/ucentral/ucentral.uc /etc/ucentral/ucentral.cfg.0000000002 > /dev/null
		rm /etc/ucentral/ucentral.cfg.0000000002
	}

	[ -f /tmp/ucentral.version ] || cat /etc/openwrt_release | grep DISTRIB_REVISION= | cut -d\' -f2 > /tmp/ucentral.version

	mkdir -p /tmp/ucentral/

	#ucode -l fs /usr/share/ucentral/pstore.uc
	
	. /lib/functions.sh
	cp /etc/config-shadow/ucentral /etc/config/
	config_load 'ucentral'
	config_get serial 'config' 'serial'
	#config_get server 'config' 'server'
	#config_get port 'config' 'port'
	config_get debug 'config' 'debug' 0
	insecure=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["allow-self-signed"]')
	config_get insecure 'config' 'insecure' $insecure

	if [ -f /etc/ucentral/restrictions.json ]; then
		selfsigned=$(cat /etc/ucentral/restrictions.json | jsonfilter -e '@["allow-self-signed"]')
		[ "${selfsigned}" == "true" ] && insecure=1
	fi

	server=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["server"]')
	port=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["port"]')
	[ -n "$server" -a -n "$port" ] || return 0

	cert=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["cert"]')
	ca=$(cat /etc/ucentral/gateway.json | jsonfilter -e '@["ca"]')

	boot_cause=$(cat /tmp/pstore | jsonfilter -e '@["pstore"][-1]'.boot_cause)
	[ -z $boot_cause ] && boot_cause=coldboot
	procd_open_instance
	procd_set_param command "$PROG"
	[ -n "$serial" ] && procd_append_param command -S $serial
	procd_append_param command -s $server
	procd_append_param command -P $port
	[ "$debug" -eq 0 ] || procd_append_param command -d
	[ "$insecure" -eq 0 ] || procd_append_param command -i
	[ -n "$cert" -a -n "$ca" ] && procd_append_param command -c $cert -C $ca
	[ -z "$(mount | grep 'tmpfs on / type tmpfs')" ] || procd_append_param command -r
	procd_append_param command -b "$boot_cause"
	procd_append_param command -f "$(cat /tmp/ucentral.version)"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
