#!/bin/sh /etc/rc.common

START=99

boot() {
	case "$(board_name)" in
	hfcl,ion4xe|\
	hfcl,ion4xi)
		fw_setenv boot_count 0
		;;		
	edgecore,eap101|\
	edgecore,eap102)
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] && fw_setenv upgrade_available 1
		fw_setenv bootcount 0
		;;
	esac
}
