#!/bin/sh /etc/rc.common

START=99

boot() {
	case "$(board_name)" in
	edgecore,eap105|\
	sonicfi,rap750w-311a|\
	sonicfi,rap750e-h|\
	sonicfi,rap750e-s|\
	sonicfi,rap7110c-341x)
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] && fw_setenv upgrade_available 1
		fw_setenv bootcount 0
		;;
	esac
}
