#!/bin/sh /etc/rc.common

START=99

boot() {
	. /lib/functions.sh

	case "$(board_name)" in
	edgecore,eap105)
		ssdk_sh debug phy set 0x1 0x601FD032 0xff
		;;
	zyxel,nwa130be)
		#eth0: APPE: phyaddr 4  green:2.5G  orange:others
		ssdk_sh debug phy set 4 0x40078074 0x670
		ssdk_sh debug phy set 4 0x40078078 0x8600

		#eth1:  MHT: phyaddr 3  green:2.5G orange:others
		ssdk_sh debug phy set 3 0x40078074 0x670
		ssdk_sh debug phy set 3 0x40078078 0x8600
		;;
	esac
}
