#!/bin/sh /etc/rc.common

START=99

boot() {
	for j in 68 69 70 71 75 88 92 96; do
		echo 8 > /proc/irq/$j/smp_affinity
	done

	for j in 67 74 91 87; do
		echo 4 > /proc/irq/$j/smp_affinity
	done

	for j in 66 73 86 90 93; do
		echo 2 > /proc/irq/$j/smp_affinity
	done

	for j in 65 72 85 89; do
		echo 1 > /proc/irq/$j/smp_affinity
	done
}
