/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_RESET_CONTROLLER_MT7987
#define _DT_BINDINGS_RESET_CONTROLLER_MT7987

/* INFRA resets */
#define MT7987_INFRA_RST0_PEXTP_MAC_SWRST	0
#define MT7987_INFRA_RST1_THERM_CTRL_SWRST	1


#endif  /* _DT_BINDINGS_RESET_CONTROLLER_MT7987 */

