#!/bin/sh

uci -q batch <<-EOF
	add firewall rule
	set firewall.@rule[-1].name='Allow-APC'
	set firewall.@rule[-1].src='wan'
	set firewall.@rule[-1].proto='udp'
	set firewall.@rule[-1].dst_port='50010'
	set firewall.@rule[-1].target='ACCEPT'
	set firewall.@rule[-1].family='ipv4'
        commit firewall
	add firewall rule
	set firewall.@rule[-1].name='Allow-UCC'
	set firewall.@rule[-1].src='wan'
	set firewall.@rule[-1].proto='udp'
	set firewall.@rule[-1].dst_port='50000'
	set firewall.@rule[-1].target='ACCEPT'
	set firewall.@rule[-1].family='ipv4'
        commit firewall

EOF
