#!/bin/sh
export >> /tmp/foo

[ -e /lib/firmware/$FIRMWARE ] && exit 0


. /lib/functions.sh
. /lib/functions/system.sh

caldata_die() {
        echo "caldata: " "$*"
        exit 1
}

caldata_extract() {
        local part=$1
        local offset=$(($2))
        local count=$(($3))
        local mtd

        mtd=$(find_mtd_chardev $part)
        [ -n "$mtd" ] || caldata_die "no mtd device found for partition $part"

        dd if=$mtd of=/lib/firmware/$FIRMWARE iflag=skip_bytes bs=$count skip=$offset count=1 2>/dev/null || \
                caldata_die "failed to extract calibration data from $mtd"
}

board=$(board_name)

case "$FIRMWARE" in
ath11k/IPQ9574/hw1.0/caldata.bin)
	case "$board" in
	qcom,ipq9574-ap-al02-c15)
		caldata_extract "0:ART" 0x1000 0x20000  
		;;
	esac
	;;
*)
	exit 1
	;;
esac
