#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=09

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

boot() {
	. /lib/functions.sh
	. /lib/functions/uci-defaults.sh
	. /lib/functions/system.sh

	board=$(board_name)

	case "$board" in
	edgecore,eap112)
		echo 486 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio486/direction
		echo 0 > /sys/class/gpio/gpio486/value
		sleep 1
		echo "in" > /sys/class/gpio/gpio486/direction
		echo 486 > /sys/class/gpio/unexport
	;;
	edgecore,eap115)
		# Enable USB power for Morse Micro HaLow module via I2C GPIO expander
		i2cset -y 0 0x41 0x01 0x44
	;;
	esac
}
