#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/usr/sbin/maverick

start_service() {
	[ -f /etc/ucentral/ucentral.active ] && return 0
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}
