#!/bin/sh

. /lib/functions.sh

section_del() {
	uci delete $2.$1
}

config_load network
config_foreach section_del interface network
config_foreach section_del bridge-vlan network
config_foreach section_del device network

config_load dhcp
config_foreach section_del dhcp dhcp

config_load firewall
config_foreach section_del zone firewall
config_foreach section_del forwarding firewall
