#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
cig,wf188n|\
cig,wf194c4|\
cig,wf194c|\
cig,wf610d|\
cig,wf808|\
cig,wf196)
	ucidef_set_wifi_country 'US'
	;;
esac

board_config_flush

exit 0
