#!/bin/sh /etc/rc.common

START=80

boot() {
        bccmd -t bcsp -b 115200 -d /dev/ttyMSM1 psload -r /lib/firmware/CSR8811/pb-207-csr8x11-rev8.psr
        sleep 1
        hciattach -s 115200 /dev/ttyMSM1 any 115200
}
