#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/countrywatch.sh

supported_boards="
sonicfi,rap630w-311g
sonicfi,rap630c-311g
"
board=$( [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic" )
echo "$supported_boards" | grep -F -q -x "$board" || return 0

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn
    procd_set_param file /etc/config/wireless
    procd_close_instance
}
