#!/bin/sh /etc/rc.common

START=51
USE_PROCD=1

NAME=uchannel
PROG=/usr/libexec/uchannel.uc

service_triggers() {
	procd_add_reload_trigger usteer
}

start_service()
{
	ENABLED="$(uci -q get usteer.@usteer[-1].enabled)"
	ENABLED="${ENABLED:-1}"
	CHANNEL="$(uci -q get usteer.@usteer[-1].autochannel)"
	CHANNEL="${CHANNEL:-0}"

	[ "$ENABLED" -gt 0 ] || return
	[ "$CHANNEL" -gt 0 ] || return

	procd_open_instance
	procd_set_param command "/usr/libexec/uchannel.uc"
	procd_set_param respawn 1 300 0
	procd_close_instance
}
