#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
edgecore,eap104)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	ucidef_set_led_netdev "wan" "wan" "yellow:uplink" "eth0"
	;;
edgecore,oap101-6e|\
edgecore,oap101e)
	ucidef_set_led_netdev "wan" "wan" "red:ethernet" "eth1"
	;;
hfcl,ion4xi_w)
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "blue:wifi5" "phy0tpt"
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "blue:wifi2" "phy1tpt"
	;;
yuncore,fap650|\
yuncore,fap655)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	;;
esac

board_config_flush

exit 0
