#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

qcom_setup_interfaces()
{
	local board="$1"
	ucidef_add_switch "switch0"
	ucidef_add_switch_attr "switch0" "enable" "false"
	ucidef_add_switch_attr "switch0" "reset" "false"

	case $board in
	cig,wf186w)
		ucidef_add_switch "switch0" "4:wan" "0:lan" "1:lan" "2:lan" "3:lan" "6u@eth0"
		;;
	cig,wf186h)
		ucidef_add_switch "switch0" "4:wan" "1:lan" "2:lan" "6u@eth0"
		;;
	sonicfi,rap630c-311g|\
	cybertan,eww631-a1)
		ucidef_set_interface_wan "eth0"
		ucidef_set_interface_lan ""
		;;
	sonicfi,rap630w-311g|\
	cybertan,eww631-b1)
		ucidef_add_switch "switch1" "5:wan" "2:lan" "3:lan" "4:lan" "6u@eth0"
		;;
	udaya,a6-id2)
		ucidef_set_interface_wan "eth1"
		ucidef_set_interface_lan "eth0"
		;;
	udaya,a6-od2)
		ucidef_set_interface_wan "eth1"
		ucidef_set_interface_lan "eth0"
		;;
	edgecore,oap101|\
 	edgecore,oap101-6e|\
	edgecore,oap101e|\
	edgecore,oap101e-6e)
		ucidef_set_interface_lan "eth1"
		ucidef_set_interface_wan "eth0"
		;;
	wallys,dr5018|\
	edgecore,eap104)
		ucidef_set_interface_wan "eth0"
		ucidef_add_switch "switch1" \
			"6u@eth1" "1:lan" "2:lan" "3:lan" "4:lan"
		;;
	indio,um-325ax-v2|\
	indio,um-335ax|\
	indio,um-525axm|\
	indio,um-525axp)
		ucidef_set_interface_wan "eth1"
		ucidef_set_interface_lan "eth0"
		ucidef_add_switch "switch1" \
			"6@eth1" "1:lan" "2:lan" "3:lan" "4:lan"
		;;
	emplus,wap385c|\
	hfcl,ion4x_w|\
	hfcl,ion4xi_w)
		ucidef_set_interface_wan "eth0"
		;;
	optimcloud,d60|\
	optimcloud,d60-5g|\
	optimcloud,d50|\
	optimcloud,d50-5g)
                ucidef_set_interface_wan "eth0"
                ucidef_set_interface_lan "eth1"
                ;;
	sonicfi,rap630w-312g|\
	yuncore,fap655)
		ucidef_add_switch "switch1" \
			"6u@eth0" "1:lan" "2:lan" "3:lan" "4:lan" "5:wan"
		;;
	glinet,b3000)
		ucidef_add_switch "switch1" "6u@eth1" "1:wan" "2:lan" "3:lan"
		;;
	sonicfi,rap630e)
		ucidef_set_interface_wan "eth1"
		ucidef_set_interface_lan "eth0"
		;;
	emplus,wap581)
		ucidef_set_interface_wan "eth0 eth1"
		;;
	esac
}

qcom_setup_macs()
{
	local board="$1"

	case $board in
	cig,wf186h|\
	cig,wf186w)
		mtd=$(find_mtd_chardev "0:APPSBLENV")
		[ -z "$mtd" ] && return;
		mac=$(grep BaseMacAddress= $mtd | cut -dx -f2)
		[ -z "$mac" ] && return;
		wan_mac=$(macaddr_canonicalize $mac)
		ucidef_set_network_device_mac eth0 $wan_mac
		ip link set eth0 address $wan_mac
		;;
	sonicfi,rap630c-311g|\
	sonicfi,rap630w-311g|\
	cybertan,eww631-a1|\
	cybertan,eww631-b1)
		mtd=$(find_mtd_chardev "0:APPSBLENV")
		[ -z "$mtd" ] && return;
		mac=$(grep BaseMacAddress= $mtd | cut -d '=' -f2)
		[ -z "$mac" ] && return;
		wan_mac=$(macaddr_canonicalize $mac)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		ucidef_set_network_device_mac eth0 $wan_mac
		ip link set eth0 address $wan_mac
		ucidef_set_label_macaddr $wan_mac
		;;
	glinet,b3000)
		wan_mac=$(cat /sys/class/net/eth1/address)
		lan_mac=$(macaddr_add "$wan_mac" 2)
		;;
	sonicfi,rap630e)
		mac=$(fw_printenv -n BaseMacAddress)
		[ -z "$mac" ] && return;
		lan_mac=$(macaddr_canonicalize $mac)
		wan_mac=$(macaddr_add "$wan_mac" 1)
		ucidef_set_network_device_mac eth1 $wan_mac
		ucidef_set_network_device_mac eth0 $lan_mac
		ip link set eth1 address $wan_mac
		ip link set eth0 address $lan_mac
		;;
	*)
		wan_mac=$(cat /sys/class/net/eth0/address)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		;;
	esac
	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
	[ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
}

board_config_update
board=$(board_name)
qcom_setup_interfaces $board
qcom_setup_macs $board
board_config_flush

exit 0
