#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

qcom_setup_interfaces()
{
	local board="$1"
	ucidef_add_switch "switch0"
	ucidef_add_switch_attr "switch0" "enable" "false"
	ucidef_add_switch_attr "switch0" "reset" "false"

	case $board in
	edgecore,oap101-6e|\
	edgecore,oap101e)
		ucidef_set_interface_lan "eth0"
		ucidef_set_interface_wan "eth1"
		;;
	edgecore,eap104)
		ucidef_set_interface_wan "eth0"
		ucidef_add_switch "switch1" \
			"6@eth1" "1:lan" "2:lan" "3:lan" "4:lan"
		;;
	hfcl,ion4xi_w)
		ucidef_set_interface_wan "eth0"
		;;
	yuncore,fap655)
		ucidef_add_switch "switch1" \
			"6@eth0" "1:lan" "2:lan" "3:lan" "4:lan" "5:wan"
		;;
	esac
}

qcom_setup_macs()
{
	local board="$1"

	case $board in
	*)
		wan_mac=$(cat /sys/class/net/eth0/address)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		;;
	esac
	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
	[ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
}

board_config_update
board=$(board_name)
qcom_setup_interfaces $board
qcom_setup_macs $board
board_config_flush

exit 0
