#!/bin/sh /etc/rc.common

START=99

boot() {
	case $(board_name) in
	edgecore,eap111|\
	edgecore,eap112)
		bootcount=$(fw_printenv -n bootcount)
		[ "$bootcount" != 0 ] && fw_setenv bootcount 0
		# enable dualboot
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] && fw_setenv upgrade_available 1
		;;
	esac
}
