#!/bin/sh /etc/rc.common

START=10
STOP=10

. /lib/functions.sh

set_fw_version() {
#check the image in the other Bank and set it as inactivefw
	cur_boot_part=$1
	ACTIVE_FW_VERSION=`sed -n 's/FW_IMAGE_ACTIVE:\(.*\)/\1/p' < /usr/opensync/.versions`
	case "$cur_boot_part" in
	1)
		fw_setenv bank1_fw $ACTIVE_FW_VERSION
		INACTIVE_FW_VERSION=`/usr/sbin/fw_printenv -n bank2_fw` || INACTIVE_FW_VERSION="unknown"
		;;
	2)
		fw_setenv bank2_fw $ACTIVE_FW_VERSION
		INACTIVE_FW_VERSION=`/usr/sbin/fw_printenv -n bank1_fw` || INACTIVE_FW_VERSION="unknown"
		;;
	*)
		INACTIVE_FW_VERSION="unknown"
		;;
	esac


	uci set system.tip.inactivefw="${INACTIVE_FW_VERSION}"
	uci commit system
}

start() {
	case "$(board_name)" in
	linksys,ea8300)
		cur_boot_part="$(/usr/sbin/fw_printenv -n boot_part)"
		set_fw_version "${cur_boot_part}"
		;;
	edgecore,ecw5410 |\
	edgecore,eap101)
		cur_boot_part="$(/usr/sbin/fw_printenv -n active)"
		set_fw_version "${cur_boot_part}"
		;;

	*)
		;;
	esac
}

stop() {
	echo "stop"
}
