#!/bin/sh

# make sure we have a tar file
[ -f /tmp/certs.tar ] || exit 1

. /lib/functions.sh

# amke sure the cert partition is mounted
cert_mount=$(grep certificates /proc/mounts)
[ -z "$cert_mount" ] && mount_certs

# validate cert volume
cert_fs=$(grep certificates /proc/mounts | cut -d " " -f 3)
[ "$cert_fs" != "ubifs" -a "$cert_fs" != "squashfs" ] && exit 1

# extract the certificates
mkdir -p /tmp/certs
tar x -C /tmp/certs -f /tmp/certs.tar

# make sure the required files exist
[ -f /tmp/certs/cas.pem -a -f /tmp/certs/key.pem -a -f /tmp/certs/cert.pem ] || exit 1
[ -f /tmp/certs/gateway.json -o -f /tmp/certs/dev-id ] || exit 1

case "$cert_fs" in
	ubifs)
		# copy the certificates to /etc
		cp /tmp/certs/*.pem /certificates

		# copy dev-id or gateway.json
		for a in dev-id gateway.json; do
			if [ -f /tmp/certs/$a ]; then
				cp /tmp/certs/$a /certificates
			else
				rm -f /certificates/$a
			fi
		done
		;;
	squashfs)
		mtd=$(find_mtd_index certificates)
		if [ -f /tmp/certs/squashfs ]; then
			# write the squashfs image to the cert partition
			mtd -e /dev/mtd$mtd write /tmp/certs/squashfs /dev/mtd$mtd
		else
			# make a squashfs image and write it to the cert partition
			mksquashfs /tmp/certs /tmp/certs.sqsh -comp xz -noappend
			mtd -e /dev/mtd$mtd write /tmp/certs.sqsh /dev/mtd$mtd
			rm -f /tmp/certs.sqsh
		fi
		umount /certificates
		mount_certs
		;;
esac

# cleanup
rm -rf /tmp/certs /tmp/certs.tar

exit 0
