#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
wallys,dr5018)
	ucidef_set_led_netdev "wan" "wan" "green:uplink" "eth0"
	;;
edgecore,eap104)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	ucidef_set_led_netdev "wan" "wan" "yellow:uplink" "eth0"
        ucidef_set_led_default "power" "POWER" "green:power" "on"
	;;
indio,um-325ax-v2|\
indio,um-335ax|\
indio,um-525axm|\
indio,um-525axp)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "led_2g" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "led_5g" "phy1tpt"
	ucidef_set_led_default "power" "POWER" "led_sys" "on"
	;;
cig,wf186h|\
cig,wf186w)
        ucidef_set_led_default "power" "POWER" "green:status" "on"
	;;
cybertan,eww631-a1|\
cybertan,eww631-b1)
        ucidef_set_led_default "power" "POWER" "sys:blue" "on"
	;;
sonicfi,rap630w-312g)
	ucidef_set_led_default "power" "POWER" "red:power" "on"
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	;;
sonicfi,rap630c-311g|\
sonicfi,rap630w-311g)
        ucidef_set_led_default "power" "POWER" "pwm:blue" "on"
	;;
sonicfi,rap630e)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	ucidef_set_led_default "power" "POWER" "green:power" "on"
	;;
edgecore,oap101|\
edgecore,oap101-6e|\
edgecore,oap101e|\
edgecore,oap101e-6e)
	ucidef_set_led_netdev "wan" "wan" "red:ethernet" "eth1"
        ucidef_set_led_default "power" "POWER" "blue:management" "on"
	;;
emplus,wap385c)
	ucidef_set_led_default "ledr" "LEDR" "sys:red" "on"
	ucidef_set_led_default "ledg" "LEDG" "sys:green" "on"
	ucidef_set_led_default "ledb" "LEDB" "sys:blue" "on"
	;;
hfcl,ion4x_w|\
hfcl,ion4xi_w)
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "blue:wifi5" "phy0tpt"
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "blue:wifi2" "phy1tpt"
	;;
yuncore,fap650|\
yuncore,fap655)
	ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy0tpt"
	ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy1tpt"
	;;
esac

board_config_flush

exit 0
