#!/bin/sh

#rm -f /etc/rc.local
#cp -f /etc/loop.local /etc/rc.local

crontab -r

/etc/init.d/cron enable

/etc/init.d/cron start

sleep 60

crontab -l | { cat; echo "*/3 * * * * /bin/sh /etc/ucentral_check.sh >> /tmp/ucentral_check";} | crontab -

crontab -l | { cat; echo "* */4 * * * rm -rf /tmp/ucentral_check";} | crontab -

/etc/init.d/cron restart
