#!/bin/sh /etc/rc.common

USE_PROCD=1
PROG=/usr/bin/ucode

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -l uci -l fs /usr/share/ucentral/firstcontact.uc
	procd_set_param respawn 1 10 0
	procd_close_instance
}
