#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=90

PROG="/usr/opensync/bin/dm"
OPENSYNC_DB=/usr/opensync/etc/conf.db.bck
OPENSYNC_SCHEMA=/usr/opensync/etc/opensync.ovsschema
OVS_DB_DIR=/var/run/openvswitch
OVS_DB=/var/run/openvswitch/conf.db
CERTS_DEST_PATH=/var/run/openvswitch/certs
CERTS_SRC_PATH=/usr/opensync/certs

start_ovs() {
        echo "Starting OVS"
	if [ ! -d ${OVS_DB_DIR} ]; then
	    mkdir -p ${OVS_DB_DIR} 
	fi
        cp ${OPENSYNC_DB} ${OVS_DB}
        procd_open_instance
        procd_set_param command /bin/sh
        procd_append_param command /usr/share/openvswitch/scripts/ovs-ctl
        procd_append_param command start --db-file=${OVS_DB} --db-schema=${OPENSYNC_SCHEMA} --system-id=1
        procd_close_instance
}

stop_ovs() {
        echo "Stopping OVS"
        /usr/share/openvswitch/scripts/ovs-ctl stop
}

start_service() {
    stop_ovs
    start_ovs
    procd_open_instance
    echo "Setting certificates"
    mkdir -p ${CERTS_DEST_PATH}
    cp ${CERTS_SRC_PATH}/* ${CERTS_DEST_PATH}/
    echo "Starting OpenSync"
    procd_set_param command ${PROG}
    procd_close_instance
}

stop_service() {
    stop_ovs
    echo "Removing certificates"
    rm -rf ${CERTS_DEST_PATH}
    echo "Killing managers"
    killall dm wm sm cm nm lm qm cmdm rrm um uccm
}
