#!/bin/sh

# This has been copied from https://github.com/openwrt/openwrt which is under GPL-2.0-only license
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0-only

[ "${ACTION}" = "add" ] && {
	/sbin/wifi config
}
