#!/bin/sh

[ "$ACTION" = "add" ] || exit 0

net=$(uci get wireless.${DEVICENAME}.network)
vid=$(uci get wireless.${DEVICENAME}.vid)

[ -z "$net" -o -z "$vid" -o "$vid" = 0 ] && exit 0

bridge vlan add vid $vid dev br-lan self
bridge vlan add vid $vid dev br-wan self
bridge vlan add vid $vid dev $(uci get network.wan.ifname)
bridge vlan add pvid $vid vid $vid dev ${DEVICENAME} untagged
exit 0
