#
# Makefile for the input misc lsm303agr driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_LSM303AGR) += lsm303agr_acc.o lsm303agr_mag.o lsm303agr_acc_i2c.o lsm303agr_mag_i2c.o
