#!/bin/sh /etc/rc.common

START=99

boot() {
	case "$(board_name)" in
	edgecore,eap101|\
	edgecore,eap102)
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] || {
			fw_setenv bootcount 0
			fw_setenv upgrade_available 0
		}
		;;
	esac
}
