#!/bin/sh /etc/rc.common

START=30

boot() {
	. /lib/functions.sh

	case "$(board_name)" in
	motorola,q14)
		. /lib/upgrade/platform.sh
		# Use the 0:BTFW emmc partition as our persistent
		# certificate store
		emmcblock=$(find_mmc_part 0:BTFW)
		if [ ! -z $emmcblock ] ; then
			modprobe block2mtd
			echo "$emmcblock,512,certificates" > /sys/module/block2mtd/parameters/block2mtd
		fi
		;;
	esac
}
