#!/bin/sh /etc/rc.common

START=80

set_affinity() {
	local affinity=$1
	local name=$2
	local irq=`grep -E -m1 $name /proc/interrupts | cut -d ':' -f 1 | tail -n1 | tr -d ' '`
        [ -n "$irq" ] && {
		logger ath11k setting affinity for $name/$irq to $affinity
		echo $affinity > /proc/irq/$irq/smp_affinity
	}
}

boot() {
	. /lib/functions/system.sh

	board=$(board_name)
	case $board in
	cig,wf196)
		set_affinity 1 reo2host-destination-ring2
		set_affinity 2 reo2host-destination-ring1
		;;
	*)
		set_affinity 2 reo2host-destination-ring2
		set_affinity 1 reo2host-destination-ring1
		;;
	esac

	case $board in
	maple)
		;;
	*)
		set_affinity 8 reo2host-destination-ring4
		set_affinity 4 reo2host-destination-ring3
	
		set_affinity 8 wbm2host-tx-completions-ring3
		set_affinity 4 wbm2host-tx-completions-ring2
		set_affinity 2 wbm2host-tx-completions-ring1

		set_affinity 8 ppdu-end-interrupts-mac1
		set_affinity 8 rxdma2host-monitor-status-ring-mac1
		set_affinity 8 rxdma2host-monitor-destination-mac1
		set_affinity 8 host2rxdma-monitor-ring1
		;;
	esac

	set_affinity 4 ppdu-end-interrupts-mac2
	set_affinity 4 rxdma2host-monitor-status-ring-mac2
	set_affinity 4 rxdma2host-monitor-destination-mac2
	set_affinity 4 host2rxdma-monitor-ring2

	set_affinity 2 ppdu-end-interrupts-mac3
	set_affinity 2 rxdma2host-monitor-status-ring-mac3
	set_affinity 2 rxdma2host-monitor-destination-mac3
	set_affinity 2 host2rxdma-monitor-ring3
}

