#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
cig,wf194c4)
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth0" "tx rx link"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
	;;
edgecore,eap102|\
edgecore,oap102|\
edgecore,oap103|\
indio,um-345ax)
	ucidef_set_led_netdev "poe" "poe" "green:wan" "eth0"
        ucidef_set_led_wlan "wlan5g" "WLAN5G" "green:wifi5" "phy0tpt"
        ucidef_set_led_wlan "wlan2g" "WLAN2G" "green:wifi2" "phy1tpt"
        ucidef_set_led_wlan "power" "POWER" "green:power" "default-on"
	;;
emplus,wap380c)
	ucidef_set_led_default "power"  "POWER"  "ipq::led0" "on"
	ucidef_set_led_netdev  "wan"    "WAN"    "ipq::led1" "eth0"
	ucidef_set_led_wlan    "wlan2g" "WLAN2G" "ipq::led2" "phy1tpt"
	ucidef_set_led_wlan    "wlan5g" "WLAN5G" "ipq::led3" "phy0tpt"
	;;
sonicfi,rap630w-311g|\
sonicfi,rap650c|\
cybertan,eww631-b1)
	ucidef_set_led_default "power" "POWER" "sys:blue" "on"
	;;
cig,wf196)
        ucidef_set_led_default "power" "POWER" "green:status" "on"
	;;
esac

board_config_flush

exit 0
