// SPDX-License-Identifier: BSD-3-Clause-Clear
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#define HAL_MON_RX_PPDU_EU_STATS_TLV_SIZE_QCN9274	\
	sizeof(struct hal_rx_mon_ppdu_end_user_stats_qcn9274)

#define HAL_RX_PPDU_END_USER_STATS_INFO0_MCS_QCN9274			GENMASK(16, 13)
#define HAL_RX_PPDU_END_USER_STATS_INFO0_NSS_QCN9274			GENMASK(19, 17)

#define HAL_RX_PPDU_END_USER_STATS_INFO1_PEER_ID_QCN9274		GENMASK(13, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO1_DEVICE_ID_QCN9274		GENMASK(15, 14)
#define HAL_RX_PPDU_END_USER_STATS_INFO1_MPDU_CNT_FCS_ERR_QCN9274	GENMASK(26, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO2_MPDU_CNT_FCS_OK_QCN9274	GENMASK(10, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_FC_VALID_QCN9274		BIT(11)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_QOS_CTRL_VALID_QCN9274		BIT(12)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_HT_CTRL_VALID_QCN9274		BIT(13)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_SEQ_CTRL_VALID_QCN9274		BIT(14)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_PKT_TYPE_QCN9274		GENMASK(24, 21)

#define HAL_RX_PPDU_END_USER_STATS_INFO3_AST_INDEX_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO3_FRAME_CTRL_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO4_SEQ_CTRL_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO4_QOS_CTRL_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO5_UDP_MSDU_CNT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO5_TCP_MSDU_CNT_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO6_OTHER_MSDU_CNT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO6_TCP_ACK_MSDU_CNT_QCN9274	GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO7_TID_BITMAP_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO7_TID_EOSP_BITMAP_QCN9274	GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO8_MPDU_OK_BYTE_CNT_QCN9274	GENMASK(24, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO9_MPDU_ERR_BYTE_CNT_QCN9274	GENMASK(24, 0)

#define HAL_RX_PPDU_END_USER_STATS_INFO10_MSDU_RETRY_CNT_QCN9274	GENMASK(31, 16)
#define HAL_RX_PPDU_END_USER_STATS_INFO11_MPDU_RETRY_CNT_QCN9274	GENMASK(28, 18)

/* The below hal_rx_mon_ppdu_end_user_stats_qcn9274 structure is non-compact
 * structure for PPDU END USER STATS TLV.
 */
struct hal_rx_mon_ppdu_end_user_stats_qcn9274 {
	__le32 rsvd0;
	__le32 info0;
	__le32 info1;
	__le32 info2;
	__le32 info3;
	__le32 info4;
	__le32 ht_ctrl;
	__le32 rsvd1[2];
	__le32 info5;
	__le32 info6;
	__le32 usr_resp_ref;
	__le32 info7;
	__le32 rsvd2[4];
	__le32 info8;
	__le32 rsvd3;
	__le32 info9;
	__le32 info10;
	__le32 rsvd4;
	__le32 usr_resp_ref_ext;
	__le32 info11;
} __packed;

#define RX_MON_PPDU_END_USER_STATS_WMASK_QCN9274 \
		(PPDU_END_USER_STATS_SELECT_INFO0_MCS_NSS |          \
		 PPDU_END_USER_STATS_SELECT_INFO1_INFO02 |           \
		 PPDU_END_USER_STATS_SELECT_INFO3_INFO04 |           \
		 PPDU_END_USER_STATS_SELECT_HTCTRL |                 \
		 PPDU_END_USER_STATS_SELECT_INFO5_UDP_TCP_COUNT |    \
		 PPDU_END_USER_STATS_SELECT_INFO6_USR_RESP_REF  |    \
		 PPDU_END_USER_STATS_SELECT_INFO7_TID_BITMAP    |    \
		 PPDU_END_USER_STATS_SELECT_INFO8_MPDU_OK_COUNT |    \
		 PPDU_END_USER_STATS_SELECT_INFO9_MPDU_ERR_COUNT |   \
		 PPDU_END_USER_STATS_SELECT_INFO10_MSDU_RETRY_COUNT |\
		 PPDU_END_USER_STATS_SELECT_USR_RESP_REF_EXT_INFO11)

#define HAL_RX_PPDU_END_USER_STATS_INFO0_MCS_CMPCT_QCN9274			GENMASK(16, 13)
#define HAL_RX_PPDU_END_USER_STATS_INFO0_NSS_CMPCT_QCN9274			GENMASK(19, 17)

#define HAL_RX_PPDU_END_USER_STATS_INFO1_PEER_ID_CMPCT_QCN9274			GENMASK(13, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO1_DEVICE_ID_CMPCT_QCN9274		GENMASK(15, 14)
#define HAL_RX_PPDU_END_USER_STATS_INFO1_MPDU_CNT_FCS_ERR_CMPCT_QCN9274		GENMASK(26, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO2_MPDU_CNT_FCS_OK_CMPCT_QCN9274		GENMASK(10, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_FC_VALID_CMPCT_QCN9274			BIT(11)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_QOS_CTRL_VALID_CMPCT_QCN9274		BIT(12)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_HT_CTRL_VALID_CMPCT_QCN9274		BIT(13)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_SEQ_CTRL_VALID_CMPCT_QCN9274		BIT(14)
#define HAL_RX_PPDU_END_USER_STATS_INFO2_PKT_TYPE_CMPCT_QCN9274			GENMASK(24, 21)

#define HAL_RX_PPDU_END_USER_STATS_INFO3_AST_INDEX_CMPCT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO3_FRAME_CTRL_CMPCT_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO4_SEQ_CTRL_CMPCT_QCN9274			GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO4_QOS_CTRL_CMPCT_QCN9274			GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO5_UDP_MSDU_CNT_CMPCT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO5_TCP_MSDU_CNT_CMPCT_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO6_OTHER_MSDU_CNT_CMPCT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO6_TCP_ACK_MSDU_CNT_CMPCT_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO7_TID_BITMAP_CMPCT_QCN9274		GENMASK(15, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO7_TID_EOSP_BITMAP_CMPCT_QCN9274		GENMASK(31, 16)

#define HAL_RX_PPDU_END_USER_STATS_INFO8_MPDU_OK_BYTE_CNT_CMPCT_QCN9274		GENMASK(24, 0)
#define HAL_RX_PPDU_END_USER_STATS_INFO9_MPDU_ERR_BYTE_CNT_CMPCT_QCN9274	GENMASK(24, 0)

#define HAL_RX_PPDU_END_USER_STATS_INFO10_MSDU_RETRY_CNT_CMPCT_QCN9274		GENMASK(31, 16)
#define HAL_RX_PPDU_END_USER_STATS_INFO11_MPDU_RETRY_CNT_CMPCT_QCN9274		GENMASK(28, 18)

/* The below hal_rx_mon_ppdu_end_user_stats_compact_qcn9274 structure is tied
 * with the mask value RX_MON_PPDU_END_USER_STATS_WMASK_QCN9274.
 * If the mask value changes the structure will also change.
 */
struct hal_rx_mon_ppdu_end_user_stats_compact_qcn9274 {
	__le32 rsvd0;
	__le32 info0;
	__le32 info1;
	__le32 info2;
	__le32 info3;
	__le32 info4;
	__le32 ht_ctrl;
	__le32 rsvd1[2];
	__le32 info5;
	__le32 info6;
	__le32 usr_resp_ref;
	__le32 info7;
	__le32 rsvd2[2];
	__le32 info8;
	__le32 rsvd3;
	__le32 info9;
	__le32 info10;
	__le32 rsvd4;
	__le32 usr_resp_ref_ext;
	__le32 info11;
} __packed;
