#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0


fwcfg_symlink() {
	local chip=$1
	local path=$2

	ln -s /lib/firmware/ath10k/fwcfg-${chip}.txt /lib/firmware/${FIRMWARE}
}

case "$FIRMWARE" in                                                         
ath10k/fwcfg-ahb-a000000.wifi.txt|\
ath10k/fwcfg-ahb-a800000.wifi.txt)
	fwcfg_symlink ipq4019
	
	;;
ath10k/fwcfg-pci-0000:01:00.0.txt)
        case "$(board_name)" in
        linksys,ea8300)
                fwcfg_symlink qca9888
                ;;
	tp-link,ap2220|\
	tp-link,ec420-g1)
		fwcfg_symlink qca9984
		;;
	esac
	;;
esac

exit 0
