# Each heading starts a new configuration
# Heading should be in format "[HEADING_NAME]"
# Parsing starts after heading, stops after an empty line

# Configuration for txdesc_ring to fc_group mapping
[txdesc_fc_mapping]
# <TX_DESC_ID>=<VQ_NUM>
