/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ip_dns_telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ip_dns_telemetry.pb-c.h"
void   wc__stats__wchealth_stats__init
                     (Wc__Stats__WCHealthStats         *message)
{
  static const Wc__Stats__WCHealthStats init_value = WC__STATS__WCHEALTH_STATS__INIT;
  *message = init_value;
}
size_t wc__stats__wchealth_stats__get_packed_size
                     (const Wc__Stats__WCHealthStats *message)
{
  assert(message->base.descriptor == &wc__stats__wchealth_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wchealth_stats__pack
                     (const Wc__Stats__WCHealthStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wchealth_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wchealth_stats__pack_to_buffer
                     (const Wc__Stats__WCHealthStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wchealth_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCHealthStats *
       wc__stats__wchealth_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCHealthStats *)
     protobuf_c_message_unpack (&wc__stats__wchealth_stats__descriptor,
                                allocator, len, data);
}
void   wc__stats__wchealth_stats__free_unpacked
                     (Wc__Stats__WCHealthStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wchealth_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__wcrisk_stats__init
                     (Wc__Stats__WCRiskStats         *message)
{
  static const Wc__Stats__WCRiskStats init_value = WC__STATS__WCRISK_STATS__INIT;
  *message = init_value;
}
size_t wc__stats__wcrisk_stats__get_packed_size
                     (const Wc__Stats__WCRiskStats *message)
{
  assert(message->base.descriptor == &wc__stats__wcrisk_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wcrisk_stats__pack
                     (const Wc__Stats__WCRiskStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wcrisk_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wcrisk_stats__pack_to_buffer
                     (const Wc__Stats__WCRiskStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wcrisk_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCRiskStats *
       wc__stats__wcrisk_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCRiskStats *)
     protobuf_c_message_unpack (&wc__stats__wcrisk_stats__descriptor,
                                allocator, len, data);
}
void   wc__stats__wcrisk_stats__free_unpacked
                     (Wc__Stats__WCRiskStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wcrisk_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__wccategory_stats__init
                     (Wc__Stats__WCCategoryStats         *message)
{
  static const Wc__Stats__WCCategoryStats init_value = WC__STATS__WCCATEGORY_STATS__INIT;
  *message = init_value;
}
size_t wc__stats__wccategory_stats__get_packed_size
                     (const Wc__Stats__WCCategoryStats *message)
{
  assert(message->base.descriptor == &wc__stats__wccategory_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wccategory_stats__pack
                     (const Wc__Stats__WCCategoryStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wccategory_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wccategory_stats__pack_to_buffer
                     (const Wc__Stats__WCCategoryStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wccategory_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCCategoryStats *
       wc__stats__wccategory_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCCategoryStats *)
     protobuf_c_message_unpack (&wc__stats__wccategory_stats__descriptor,
                                allocator, len, data);
}
void   wc__stats__wccategory_stats__free_unpacked
                     (Wc__Stats__WCCategoryStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wccategory_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__wcrule_stats__init
                     (Wc__Stats__WCRuleStats         *message)
{
  static const Wc__Stats__WCRuleStats init_value = WC__STATS__WCRULE_STATS__INIT;
  *message = init_value;
}
size_t wc__stats__wcrule_stats__get_packed_size
                     (const Wc__Stats__WCRuleStats *message)
{
  assert(message->base.descriptor == &wc__stats__wcrule_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wcrule_stats__pack
                     (const Wc__Stats__WCRuleStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wcrule_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wcrule_stats__pack_to_buffer
                     (const Wc__Stats__WCRuleStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wcrule_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCRuleStats *
       wc__stats__wcrule_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCRuleStats *)
     protobuf_c_message_unpack (&wc__stats__wcrule_stats__descriptor,
                                allocator, len, data);
}
void   wc__stats__wcrule_stats__free_unpacked
                     (Wc__Stats__WCRuleStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wcrule_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__wchero_stats__init
                     (Wc__Stats__WCHeroStats         *message)
{
  static const Wc__Stats__WCHeroStats init_value = WC__STATS__WCHERO_STATS__INIT;
  *message = init_value;
}
size_t wc__stats__wchero_stats__get_packed_size
                     (const Wc__Stats__WCHeroStats *message)
{
  assert(message->base.descriptor == &wc__stats__wchero_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wchero_stats__pack
                     (const Wc__Stats__WCHeroStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wchero_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wchero_stats__pack_to_buffer
                     (const Wc__Stats__WCHeroStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wchero_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCHeroStats *
       wc__stats__wchero_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCHeroStats *)
     protobuf_c_message_unpack (&wc__stats__wchero_stats__descriptor,
                                allocator, len, data);
}
void   wc__stats__wchero_stats__free_unpacked
                     (Wc__Stats__WCHeroStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wchero_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__observation_point__init
                     (Wc__Stats__ObservationPoint         *message)
{
  static const Wc__Stats__ObservationPoint init_value = WC__STATS__OBSERVATION_POINT__INIT;
  *message = init_value;
}
size_t wc__stats__observation_point__get_packed_size
                     (const Wc__Stats__ObservationPoint *message)
{
  assert(message->base.descriptor == &wc__stats__observation_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__observation_point__pack
                     (const Wc__Stats__ObservationPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__observation_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__observation_point__pack_to_buffer
                     (const Wc__Stats__ObservationPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__observation_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__ObservationPoint *
       wc__stats__observation_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__ObservationPoint *)
     protobuf_c_message_unpack (&wc__stats__observation_point__descriptor,
                                allocator, len, data);
}
void   wc__stats__observation_point__free_unpacked
                     (Wc__Stats__ObservationPoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__observation_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__observation_window__init
                     (Wc__Stats__ObservationWindow         *message)
{
  static const Wc__Stats__ObservationWindow init_value = WC__STATS__OBSERVATION_WINDOW__INIT;
  *message = init_value;
}
size_t wc__stats__observation_window__get_packed_size
                     (const Wc__Stats__ObservationWindow *message)
{
  assert(message->base.descriptor == &wc__stats__observation_window__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__observation_window__pack
                     (const Wc__Stats__ObservationWindow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__observation_window__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__observation_window__pack_to_buffer
                     (const Wc__Stats__ObservationWindow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__observation_window__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__ObservationWindow *
       wc__stats__observation_window__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__ObservationWindow *)
     protobuf_c_message_unpack (&wc__stats__observation_window__descriptor,
                                allocator, len, data);
}
void   wc__stats__observation_window__free_unpacked
                     (Wc__Stats__ObservationWindow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__observation_window__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wc__stats__wcstats_report__init
                     (Wc__Stats__WCStatsReport         *message)
{
  static const Wc__Stats__WCStatsReport init_value = WC__STATS__WCSTATS_REPORT__INIT;
  *message = init_value;
}
size_t wc__stats__wcstats_report__get_packed_size
                     (const Wc__Stats__WCStatsReport *message)
{
  assert(message->base.descriptor == &wc__stats__wcstats_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wc__stats__wcstats_report__pack
                     (const Wc__Stats__WCStatsReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wc__stats__wcstats_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wc__stats__wcstats_report__pack_to_buffer
                     (const Wc__Stats__WCStatsReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wc__stats__wcstats_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wc__Stats__WCStatsReport *
       wc__stats__wcstats_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wc__Stats__WCStatsReport *)
     protobuf_c_message_unpack (&wc__stats__wcstats_report__descriptor,
                                allocator, len, data);
}
void   wc__stats__wcstats_report__free_unpacked
                     (Wc__Stats__WCStatsReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wc__stats__wcstats_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wc__stats__wchealth_stats__field_descriptors[11] =
{
  {
    "totalLookups",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_totallookups),
    offsetof(Wc__Stats__WCHealthStats, totallookups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cacheHits",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_cachehits),
    offsetof(Wc__Stats__WCHealthStats, cachehits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteLookups",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_remotelookups),
    offsetof(Wc__Stats__WCHealthStats, remotelookups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectivityFailures",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_connectivityfailures),
    offsetof(Wc__Stats__WCHealthStats, connectivityfailures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serviceFailures",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_servicefailures),
    offsetof(Wc__Stats__WCHealthStats, servicefailures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncategorized",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_uncategorized),
    offsetof(Wc__Stats__WCHealthStats, uncategorized),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minLatency",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_minlatency),
    offsetof(Wc__Stats__WCHealthStats, minlatency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxLatency",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_maxlatency),
    offsetof(Wc__Stats__WCHealthStats, maxlatency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "averageLatency",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_averagelatency),
    offsetof(Wc__Stats__WCHealthStats, averagelatency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cachedEntries",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_cachedentries),
    offsetof(Wc__Stats__WCHealthStats, cachedentries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cacheSize",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCHealthStats, has_cachesize),
    offsetof(Wc__Stats__WCHealthStats, cachesize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wchealth_stats__field_indices_by_name[] = {
  8,   /* field[8] = averageLatency */
  1,   /* field[1] = cacheHits */
  10,   /* field[10] = cacheSize */
  9,   /* field[9] = cachedEntries */
  3,   /* field[3] = connectivityFailures */
  7,   /* field[7] = maxLatency */
  6,   /* field[6] = minLatency */
  2,   /* field[2] = remoteLookups */
  4,   /* field[4] = serviceFailures */
  0,   /* field[0] = totalLookups */
  5,   /* field[5] = uncategorized */
};
static const ProtobufCIntRange wc__stats__wchealth_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor wc__stats__wchealth_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCHealthStats",
  "WCHealthStats",
  "Wc__Stats__WCHealthStats",
  "wc.stats",
  sizeof(Wc__Stats__WCHealthStats),
  11,
  wc__stats__wchealth_stats__field_descriptors,
  wc__stats__wchealth_stats__field_indices_by_name,
  1,  wc__stats__wchealth_stats__number_ranges,
  (ProtobufCMessageInit) wc__stats__wchealth_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__wcrisk_stats__field_descriptors[2] =
{
  {
    "risk",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Wc__Stats__WCRiskStats, has_risk),
    offsetof(Wc__Stats__WCRiskStats, risk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalHits",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Wc__Stats__WCRiskStats, has_totalhits),
    offsetof(Wc__Stats__WCRiskStats, totalhits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wcrisk_stats__field_indices_by_name[] = {
  0,   /* field[0] = risk */
  1,   /* field[1] = totalHits */
};
static const ProtobufCIntRange wc__stats__wcrisk_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wc__stats__wcrisk_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCRiskStats",
  "WCRiskStats",
  "Wc__Stats__WCRiskStats",
  "wc.stats",
  sizeof(Wc__Stats__WCRiskStats),
  2,
  wc__stats__wcrisk_stats__field_descriptors,
  wc__stats__wcrisk_stats__field_indices_by_name,
  1,  wc__stats__wcrisk_stats__number_ranges,
  (ProtobufCMessageInit) wc__stats__wcrisk_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__wccategory_stats__field_descriptors[2] =
{
  {
    "categoryId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Wc__Stats__WCCategoryStats, has_categoryid),
    offsetof(Wc__Stats__WCCategoryStats, categoryid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wcRiskStats",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Wc__Stats__WCCategoryStats, n_wcriskstats),
    offsetof(Wc__Stats__WCCategoryStats, wcriskstats),
    &wc__stats__wcrisk_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wccategory_stats__field_indices_by_name[] = {
  0,   /* field[0] = categoryId */
  1,   /* field[1] = wcRiskStats */
};
static const ProtobufCIntRange wc__stats__wccategory_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wc__stats__wccategory_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCCategoryStats",
  "WCCategoryStats",
  "Wc__Stats__WCCategoryStats",
  "wc.stats",
  sizeof(Wc__Stats__WCCategoryStats),
  2,
  wc__stats__wccategory_stats__field_descriptors,
  wc__stats__wccategory_stats__field_indices_by_name,
  1,  wc__stats__wccategory_stats__number_ranges,
  (ProtobufCMessageInit) wc__stats__wccategory_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__wcrule_stats__field_descriptors[3] =
{
  {
    "policyName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCRuleStats, policyname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ruleName",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCRuleStats, rulename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wcCategoryStats",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Wc__Stats__WCRuleStats, n_wccategorystats),
    offsetof(Wc__Stats__WCRuleStats, wccategorystats),
    &wc__stats__wccategory_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wcrule_stats__field_indices_by_name[] = {
  0,   /* field[0] = policyName */
  1,   /* field[1] = ruleName */
  2,   /* field[2] = wcCategoryStats */
};
static const ProtobufCIntRange wc__stats__wcrule_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wc__stats__wcrule_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCRuleStats",
  "WCRuleStats",
  "Wc__Stats__WCRuleStats",
  "wc.stats",
  sizeof(Wc__Stats__WCRuleStats),
  3,
  wc__stats__wcrule_stats__field_descriptors,
  wc__stats__wcrule_stats__field_indices_by_name,
  1,  wc__stats__wcrule_stats__number_ranges,
  (ProtobufCMessageInit) wc__stats__wcrule_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__wchero_stats__field_descriptors[2] =
{
  {
    "srcMac",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCHeroStats, srcmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wcRuleStats",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Wc__Stats__WCHeroStats, n_wcrulestats),
    offsetof(Wc__Stats__WCHeroStats, wcrulestats),
    &wc__stats__wcrule_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wchero_stats__field_indices_by_name[] = {
  0,   /* field[0] = srcMac */
  1,   /* field[1] = wcRuleStats */
};
static const ProtobufCIntRange wc__stats__wchero_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wc__stats__wchero_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCHeroStats",
  "WCHeroStats",
  "Wc__Stats__WCHeroStats",
  "wc.stats",
  sizeof(Wc__Stats__WCHeroStats),
  2,
  wc__stats__wchero_stats__field_descriptors,
  wc__stats__wchero_stats__field_indices_by_name,
  1,  wc__stats__wchero_stats__number_ranges,
  (ProtobufCMessageInit) wc__stats__wchero_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__observation_point__field_descriptors[2] =
{
  {
    "nodeId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__ObservationPoint, nodeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locationId",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__ObservationPoint, locationid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__observation_point__field_indices_by_name[] = {
  1,   /* field[1] = locationId */
  0,   /* field[0] = nodeId */
};
static const ProtobufCIntRange wc__stats__observation_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wc__stats__observation_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.ObservationPoint",
  "ObservationPoint",
  "Wc__Stats__ObservationPoint",
  "wc.stats",
  sizeof(Wc__Stats__ObservationPoint),
  2,
  wc__stats__observation_point__field_descriptors,
  wc__stats__observation_point__field_indices_by_name,
  1,  wc__stats__observation_point__number_ranges,
  (ProtobufCMessageInit) wc__stats__observation_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__observation_window__field_descriptors[2] =
{
  {
    "startedAt",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Wc__Stats__ObservationWindow, has_startedat),
    offsetof(Wc__Stats__ObservationWindow, startedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endedAt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Wc__Stats__ObservationWindow, has_endedat),
    offsetof(Wc__Stats__ObservationWindow, endedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__observation_window__field_indices_by_name[] = {
  1,   /* field[1] = endedAt */
  0,   /* field[0] = startedAt */
};
static const ProtobufCIntRange wc__stats__observation_window__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wc__stats__observation_window__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.ObservationWindow",
  "ObservationWindow",
  "Wc__Stats__ObservationWindow",
  "wc.stats",
  sizeof(Wc__Stats__ObservationWindow),
  2,
  wc__stats__observation_window__field_descriptors,
  wc__stats__observation_window__field_indices_by_name,
  1,  wc__stats__observation_window__number_ranges,
  (ProtobufCMessageInit) wc__stats__observation_window__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wc__stats__wcstats_report__field_descriptors[5] =
{
  {
    "wcProvider",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCStatsReport, wcprovider),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observationPoint",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCStatsReport, observationpoint),
    &wc__stats__observation_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observationWindow",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCStatsReport, observationwindow),
    &wc__stats__observation_window__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wcHealthStats",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Wc__Stats__WCStatsReport, wchealthstats),
    &wc__stats__wchealth_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wcHeroStats",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Wc__Stats__WCStatsReport, n_wcherostats),
    offsetof(Wc__Stats__WCStatsReport, wcherostats),
    &wc__stats__wchero_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wc__stats__wcstats_report__field_indices_by_name[] = {
  1,   /* field[1] = observationPoint */
  2,   /* field[2] = observationWindow */
  3,   /* field[3] = wcHealthStats */
  4,   /* field[4] = wcHeroStats */
  0,   /* field[0] = wcProvider */
};
static const ProtobufCIntRange wc__stats__wcstats_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor wc__stats__wcstats_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wc.stats.WCStatsReport",
  "WCStatsReport",
  "Wc__Stats__WCStatsReport",
  "wc.stats",
  sizeof(Wc__Stats__WCStatsReport),
  5,
  wc__stats__wcstats_report__field_descriptors,
  wc__stats__wcstats_report__field_indices_by_name,
  1,  wc__stats__wcstats_report__number_ranges,
  (ProtobufCMessageInit) wc__stats__wcstats_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
