#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/bin/ucentralgw

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command --file /etc/ucentral/ucentral.properties
	procd_set_param respawn 3600 5 0
	procd_add_mdns "ucentral" "tcp" "15002" "daemon=ucentralgw"
	procd_close_instance
}
