#!/bin/sh /etc/rc.common

START=99

boot() {
	case $(board_name) in
	alfa-network,ap120c-ac)
		[ -n "$(fw_printenv bootcount changed 2>/dev/null)" ] &&\
			echo -e "bootcount\nchanged\n" | /usr/sbin/fw_setenv -s -
		;;
	linksys,ea6350v3|\
	linksys,ea8300|\
	linksys,mr8300)
		mtd resetbc s_env || true
		;;
	edgecore,ecw5211)
		part="$(awk -F 'ubi.mtd=' '{printf $2}' /proc/cmdline | cut -d " " -f1)"
		case "$part" in
		rootfs1|\
		rootfs2)
			avail=$(fw_printenv -n upgrade_available)
			[ ${avail} -ne 1 ] && fw_setenv upgrade_available 1
			fw_setenv bootcount 0
			;;
		esac
		;;
	edgecore,spw2ac1200|\
	edgecore,spw2ac1200-lan-poe)
		avail=$(fw_printenv -n upgrade_available)
		[ ${avail} -eq 0 ] || {
			fw_setenv upgrade_available 0
			fw_setenv bootcount 0
		}
		;;
	esac
}
