# QTI IPQ Sound Card Support
snd-soc-ipq-lpass-objs := ipq-lpass.o
snd-soc-ipq9574-lpass-pcm-raw-objs := ipq9574-lpass-pcm.o ipq9574-pcm-raw-lb-test.o

obj-$(CONFIG_SND_SOC_IPQ_LPASS) += snd-soc-ipq-lpass.o
obj-$(CONFIG_SND_SOC_IPQ9574_LPASS_PCM_RAW) += snd-soc-ipq9574-lpass-pcm-raw.o
