#!/bin/sh /etc/rc.common

START=30

boot() {
	. /lib/functions.sh

	case "$(board_name)" in
	cig,wf194c|\
	cig,wf194c4|\
	cig,wf196)
		aq-fw-download /lib/firmware/AQR-G4_v5.5.6-AQR_CIG_WIFI_ID44858_VER1745.cld miireg 0 > /dev/null
		sleep 1
		ssdk_sh debug phy set 0 0x4004c441 0x8
		;;
	edgecore,eap106)
		aq-fw-download /lib/firmware/AQR-G4_v5.5.6-AQR_CIG_WIFI_ID44858_VER1745.cld miireg 8 > /dev/null
		sleep 1
		ssdk_sh debug phy set 8 0x4004c441 0x8
		;;
	esac

	case "$(board_name)" in
	cig,wf196)
		# setup the leds
		ssdk_sh debug phy set 0 0x401ec431 0xc00f
		ssdk_sh debug phy set 0 0x401ec430 0x806f
		;;
	esac
}
