/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef UBUS_COLLECTOR_H_INCLUDED
#define UBUS_COLLECTOR_H_INCLUDED

#include <stdbool.h>
#include <stdint.h>
#include <syslog.h>
#include "target.h"

#include "evsched.h"
#include "libubus.h"
#include "dpp_events.h"
#include "radio.h"
#include "ubus.h"

/* Initialize ubus collector */
int ubus_collector_init(void);

/* Clean up ubus collector objects */
void ubus_collector_cleanup(void);

#define UBUS_SOCKET "/var/run/ubus.sock"

/* Poll bss list after this many seconds */
#define UBUS_BSS_POLLING_DELAY 7

/* Poll sessions after this many seconds */
#define UBUS_SESSIONS_POLLING_DELAY 9

/* Poll transactions after this many seconds */
#define UBUS_TRANSACTIONS_POLLING_DELAY 9

/* Poll the session and transaction clearing 'garbage collector' after this many seconds */
#define UBUS_GARBAGE_COLLECTION_DELAY 1

#define UBUS_OBJ_LEN 64

enum {
	UBUS_COLLECTOR_SESSIONS,
	__UBUS_SESSIONS_MAX,
};

enum {
	CLIENT_ASSOC_EVENT,
	CLIENT_AUTH_EVENT,
	CLIENT_DISCONNECT_EVENT,
	CLIENT_FAILURE_EVENT,
	CLIENT_FIRST_DATA_EVENT,
	CLIENT_TIMEOUT_EVENT,
	CLIENT_IP_EVENT,
	CLIENT_SESSION_ID,
	__CLIENT_EVENTS_MAX,
};

enum {
	CLIENT_ASSOC_ASSOC_TYPE,
	CLIENT_ASSOC_TIMESTAMP,
	CLIENT_ASSOC_BAND,
	CLIENT_ASSOC_INTERNAL_SC,
	CLIENT_ASSOC_RSSI,
	CLIENT_ASSOC_SESSION_ID,
	CLIENT_ASSOC_SSID,
	CLIENT_ASSOC_STA_MAC,
	CLIENT_ASSOC_USING11K,
	CLIENT_ASSOC_USING11R,
	CLIENT_ASSOC_USING11V,
	__CLIENT_ASSOC_MAX,
};

enum {
	CLIENT_AUTH_SESSION_ID,
	CLIENT_AUTH_TIMESTAMP,
	CLIENT_AUTH_BAND,
	CLIENT_AUTH_AUTH_STATUS,
	CLIENT_AUTH_AUTH_SSID,
	CLIENT_AUTH_STA_MAC,
	__CLIENT_AUTH_MAX,
};

enum {
	CLIENT_DISCONNECT_SESSION_ID,
	CLIENT_DISCONNECT_TIMESTAMP,
	CLIENT_DISCONNECT_STA_MAC,
	CLIENT_DISCONNECT_BAND,
	CLIENT_DISCONNECT_RSSI,
	CLIENT_DISCONNECT_INTERNAL_RC,
	CLIENT_DISCONNECT_SSID,
	__CLIENT_DISCONNECT_MAX,
};

enum {
	CLIENT_FIRST_DATA_STA_MAC,
	CLIENT_FIRST_DATA_SESSION_ID,
	CLIENT_FIRST_DATA_TIMESTAMP,
	CLIENT_FIRST_DATA_TX_TIMESTAMP,
	CLIENT_FIRST_DATA_RX_TIMESTAMP,
	__CLIENT_FIRST_DATA_MAX,
};

enum {
	CLIENT_IP_SESSION_ID,
	CLIENT_IP_TIMESTAMP,
	CLIENT_IP_STA_MAC,
	CLIENT_IP_IP_ADDRESS,
	__CLIENT_IP_MAX,
};

enum {
	BSS_LIST_BSS_LIST,
	__BSS_LIST_DATA_MAX,
};

enum {
	BSS_OBJECT_NAME,
	__BSS_TABLE_MAX,
};

enum {
	UBUS_COLLECTOR_TRANSACTIONS,
	__UBUS_TRANSACTIONS_MAX,
};

enum {
	DHCP_ACK_EVENT,
	DHCP_NAK_EVENT,
	DHCP_OFFER_EVENT,
	DHCP_INFORM_EVENT,
	DHCP_DECLINE_EVENT,
	DHCP_REQUEST_EVENT,
	DHCP_DISCOVER_EVENT,
	DHCP_X_ID,
	__DHCP_EVENTS_MAX,
};

enum {
	DHCP_ACK_X_ID,
	DHCP_ACK_VLAN_ID,
	DHCP_ACK_DHCP_SERVER_IP,
	DHCP_ACK_CLIENT_IP,
	DHCP_ACK_RELAY_IP,
	DHCP_ACK_DEVICE_MAC_ADDRESS,
	DHCP_ACK_TIMESTAMP_MS,
	DHCP_ACK_SUBNET_MASK,
	DHCP_ACK_PRIMARY_DNS,
	DHCP_ACK_SECONDARY_DNS,
	DHCP_ACK_LEASE_TIME,
	DHCP_ACK_RENEWAL_TIME,
	DHCP_ACK_REBINDING_TIME,
	DHCP_ACK_TIME_OFFSET,
	DHCP_ACK_GATEWAY_IP,
	__DHCP_ACK_MAX,
};

enum {
	DHCP_NAK_X_ID,
	DHCP_NAK_VLAN_ID,
	DHCP_NAK_DHCP_SERVER_IP,
	DHCP_NAK_CLIENT_IP,
	DHCP_NAK_RELAY_IP,
	DHCP_NAK_DEVICE_MAC_ADDRESS,
	DHCP_NAK_TIMESTAMP_MS,
	DHCP_NAK_FROM_INTERNAL,
	__DHCP_NAK_MAX,
};

enum {
	DHCP_OFFER_X_ID,
	DHCP_OFFER_VLAN_ID,
	DHCP_OFFER_DHCP_SERVER_IP,
	DHCP_OFFER_CLIENT_IP,
	DHCP_OFFER_RELAY_IP,
	DHCP_OFFER_DEVICE_MAC_ADDRESS,
	DHCP_OFFER_TIMESTAMP_MS,
	DHCP_OFFER_FROM_INTERNAL,
	__DHCP_OFFER_MAX,
};

enum {
	DHCP_INFORM_X_ID,
	DHCP_INFORM_VLAN_ID,
	DHCP_INFORM_DHCP_SERVER_IP,
	DHCP_INFORM_CLIENT_IP,
	DHCP_INFORM_RELAY_IP,
	DHCP_INFORM_DEVICE_MAC_ADDRESS,
	DHCP_INFORM_TIMESTAMP_MS,
	__DHCP_INFORM_MAX,
};

enum {
	DHCP_DECLINE_X_ID,
	DHCP_DECLINE_VLAN_ID,
	DHCP_DECLINE_DHCP_SERVER_IP,
	DHCP_DECLINE_CLIENT_IP,
	DHCP_DECLINE_RELAY_IP,
	DHCP_DECLINE_DEVICE_MAC_ADDRESS,
	DHCP_DECLINE_TIMESTAMP_MS,
	__DHCP_DECLINE_MAX,
};

enum {
	DHCP_REQUEST_X_ID,
	DHCP_REQUEST_VLAN_ID,
	DHCP_REQUEST_DHCP_SERVER_IP,
	DHCP_REQUEST_CLIENT_IP,
	DHCP_REQUEST_RELAY_IP,
	DHCP_REQUEST_DEVICE_MAC_ADDRESS,
	DHCP_REQUEST_TIMESTAMP_MS,
	DHCP_REQUEST_HOSTNAME,
	__DHCP_REQUEST_MAX,
};

enum {
	DHCP_DISCOVER_X_ID,
	DHCP_DISCOVER_VLAN_ID,
	DHCP_DISCOVER_DHCP_SERVER_IP,
	DHCP_DISCOVER_CLIENT_IP,
	DHCP_DISCOVER_RELAY_IP,
	DHCP_DISCOVER_DEVICE_MAC_ADDRESS,
	DHCP_DISCOVER_TIMESTAMP_MS,
	DHCP_DISCOVER_HOSTNAME,
	__DHCP_DISCOVER_MAX,
};

#endif /* UBUS_COLLECTOR_H_INCLUDED */
