#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/udnssnoop

service_triggers() {
	procd_add_reload_trigger qosify
}

start_service() {
	local device=$(uci get qosify.@device[0].name)
	[ -z "$device" ] && return

	procd_open_instance
	procd_set_param command "$PROG" $device
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	restart
}
