# INI file
# This file will contain global INI configurations

# Datapath configuration Parameters
# Add the data path specific config parameters below
# E.g For DP_RXDMA_BUF_RING
# dp_rxdma_buf_ring=8192

# Control path configuration Parameters
# Add the control path specific config parameters below
# E.g for TID-to-link mapping
# 0 - T2LM is not supported by the MLD
# 1 - MLD only supports the mapping of all TIDs to the same link set
# t2lm_enable=1

# Memory profile setting
# 0 - Indicates the system is not a low memory
# 1 - Implies system is low memory
low_mem_system=0

# Carrier_profile_config
# BIT 0 -> enable/disable ssid prioritization configurations
# BIT 1 : 31 Reserved
#
carrier_profile_config=0

#Rep STA OFDMA support
#0 - default value
#1 - Enable 1 Radio(1 bit)
#3 - Enable 2 Radios(2 bit)
#7 - Enable 3 Radios(3 bit)
rep_ul_resp=0
