#!/bin/sh

GPS_SUPPORT=/var/run/gps_support
GPS_DUMP_TMP=/tmp/ttyGpsDump.dat
GPS_DUMP=/tmp/out_GpsDump.tr

#  check if GPS module is present
if [ -f "$GPS_SUPPORT" ]; then
  # no. of seconds GPS data will be captured for (default = 3)
  if [ -z "$1" ]
  then
    sec=3
  else
    sec=$1
    expr $sec + 0 &>/dev/null
    [ $? -eq 0 ] || sec=3
  fi

  echo "catpure data for : $sec seconds"

  # minimum no. of satellites required (default = 5)
  if [ -z "$2" ]
  then
    sate=5
  else
    sate=$2
    expr $sate + 0 &>/dev/null
    [ $? -eq 0 ] || sate=5
  fi

  echo "require satellite is : $sate "

  [ -f "$GPS_DUMP_TMP" ] && rm -f "$GPS_DUMP_TMP"
  [ -f "$GPS_DUMP" ] && rm -f "$GPS_DUMP"

  # change tty port to GPS
  echo 0 > /sys/class/gpio/ble_enable/value
  # change stty for GPS output
  stty raw -echo -echoe -echok -F /dev/ttyMSM1 115200

  i2cset -f -y 0 0x74 0x07 0x12
  i2cset -f -y 0 0x74 0x03 0xBE

  exec 3</dev/ttyMSM1
  cat <&3 > "$GPS_DUMP_TMP" &

  PID=$!

  i2cset -f -y 0 0x74 0x03 0xB6
  sleep $sec

  kill $PID
  wait $PID 2>/dev/null
  exec 3<&-
  i2cset -f -y 0 0x74 0x03 0xBE

  sed 's/...$//' "$GPS_DUMP_TMP" > "$GPS_DUMP"
  rm -f "$GPS_DUMP_TMP"

  # change tty to BLE
  echo 1 > /sys/class/gpio/ble_enable/value
fi
