#!/usr/bin/env python3
import sys
import os
import argparse
import kconfiglib

KCONFIG_CONFIG = os.environ.get("KCONFIG_CONFIG", ".config")
ARGS = None

def parse_args():
    global ARGS

    arg_main = argparse.ArgumentParser(
            description = 'Tool for generating minimalistic "diffconfigs" (diff between default and current config)')

    arg_main.add_argument(
            '-c', '--config',
            default = KCONFIG_CONFIG,
            help='Location of the configuration file (default: %s)' % KCONFIG_CONFIG)

    arg_main.add_argument(
            '-n', '--unminimize',
            default = False,
            action = 'store_true',
            help='Write full config. This can be used to reconstruct a full config file from a diffconfig.')

    arg_main.add_argument(
            '-o', '--out',
            default = None,
            help='Output file (default: same as config)')

    arg_main.add_argument(
            'KCONFIG',
            nargs='?',
            help="Path to the Kconfig file (default: Kconfig)",
            default = "Kconfig")

    ARGS = arg_main.parse_args()

parse_args()

kconf = kconfiglib.Kconfig(ARGS.KCONFIG)
kconf.load_config(ARGS.config)

outfile = ARGS.out if ARGS.out else ARGS.config

if ARGS.unminimize:
    kconf.write_config(outfile)
else:
    kconf.write_min_config(outfile)
