#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
sercomm,ap72tip-v4|\
sercomm,ap72tip)
	ucidef_set_led_default "power" "POWER" "blue:status" "on"
	ucidef_set_led_netdev "wan_link" "wan_link" "green:phy" "eth0" "link"
	ucidef_set_led_netdev "wan_act" "wan_act" "yellow:phy" "eth0" "rx tx"
	;;
sonicfi,rap7110c-341x|\
sonicfi,rap750e-h|\
sonicfi,rap750w-311a)
	ucidef_set_led_default "power" "POWER" "pwm:blue" "on"
	;;
zyxel,nwa130be)
	#eth0: APPE: phyaddr 4  green:2.5G  orange:others
	ssdk_sh debug phy set 4 0x40078074 0x670
	ssdk_sh debug phy set 4 0x40078078 0x8600

	#eth1:  MHT: phyaddr 3  green:2.5G orange:others
	ssdk_sh debug phy set 3 0x40078074 0x670
	ssdk_sh debug phy set 3 0x40078078 0x8600
	;;
esac

board_config_flush

exit 0
