#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
sercomm,ap72tip-v4|\
sercomm,ap72tip)
	ucidef_set_led_default "power" "POWER" "blue:status" "on"
	ucidef_set_led_netdev "wan_link" "wan_link" "green:phy" "eth0" "link"
	ucidef_set_led_netdev "wan_act" "wan_act" "yellow:phy" "eth0" "rx tx"
	;;
sonicfi,rap7110c-341x|\
sonicfi,rap750e-h|\
sonicfi,rap750w-311a)
	ucidef_set_led_default "power" "POWER" "pwm:blue" "on"
	;;
esac

board_config_flush

exit 0
