#!/bin/sh

. /lib/functions/uci-defaults.sh
. /lib/functions.sh
. /lib/functions/system.sh

ipq54xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	cig,wf197)
		# TODO update WAN LAN interfaces properly
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		ucidef_add_switch "switch1" "0u@eth1" "3:lan" "2:lan"
		;;
	esac
}

qcom_setup_macs()
{
        local board="$1"
        case $board in
        cig,wf197)
		# TODO update MACs accordingly
                mtd=$(find_mtd_chardev "0:APPSBLENV")
                [ -z "$mtd" ] && return;
                mac=$(grep eth1addr= $mtd | cut -d= -f2)
                [ -z "$mac" ] && return;
                wan_mac=$(macaddr_canonicalize $mac)
                lan_mac=$(macaddr_add "$wan_mac" 1)
                ucidef_set_network_device_mac eth0 $wan_mac
                ucidef_set_network_device_mac eth1 $lan_mac
                ucidef_set_label_macaddr $wan_mac
                ucidef_set_wireless_macaddr_base 2g $(macaddr_add "$wan_mac" 2)
                ucidef_set_wireless_macaddr_base 5g $(macaddr_add "$wan_mac" 3)
                ucidef_set_wireless_macaddr_base 6g $(macaddr_add "$wan_mac" 4)
                ;;
        esac
        [ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
        [ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
        [ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
}

board_config_update
board=$(board_name)
ipq54xx_setup_interfaces $board
qcom_setup_macs $board
board_config_flush

exit 0
