#!/bin/sh

. /lib/functions/uci-defaults.sh
. /lib/functions.sh
. /lib/functions/system.sh

ipq54xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	cig,wf197)
		ucidef_set_interface_wan "eth0 eth1"
		;;
	esac
}

qcom_setup_macs()
{
        local board="$1"
        case $board in
        cig,wf197)
                mmc=$(find_mmc_part "0:APPSBLENV")
                [ -z "$mmc" ] && return;
                mac=$(grep eth1addr= $mmc | cut -d= -f2)
                [ -z "$mac" ] && return;
                wan_mac=$(macaddr_canonicalize $mac)
                lan_mac=$(macaddr_add "$wan_mac" 1)
                ucidef_set_network_device_mac eth0 $wan_mac
                ucidef_set_network_device_mac eth1 $lan_mac
                ucidef_set_label_macaddr $wan_mac
                # Derive wireless base MACs and ensure they are valid unicast
                # addresses (clear multicast bit0, set locally-administered bit1)
                local wifi_2g_mac wifi_5g_mac wifi_6g_mac
                wifi_2g_mac=$(macaddr_add "$wan_mac" 2)
                wifi_5g_mac=$(macaddr_add "$wan_mac" 3)
                wifi_6g_mac=$(macaddr_add "$wan_mac" 4)
                wifi_2g_mac=$(macaddr_unsetbit_mc "$(macaddr_setbit_la "$wifi_2g_mac")")
                wifi_5g_mac=$(macaddr_unsetbit_mc "$(macaddr_setbit_la "$wifi_5g_mac")")
                wifi_6g_mac=$(macaddr_unsetbit_mc "$(macaddr_setbit_la "$wifi_6g_mac")")
                ucidef_set_wireless_macaddr_base 2g "$wifi_2g_mac"
                ucidef_set_wireless_macaddr_base 5g "$wifi_5g_mac"
                ucidef_set_wireless_macaddr_base 6g "$wifi_6g_mac"
                ;;
        *)
                wan_mac=$(cat /sys/class/net/eth1/address)
                lan_mac=$(macaddr_add "$wan_mac" 1)
                ;;
        esac
        [ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
        [ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
        [ -n "$wan_mac" ] && ucidef_set_label_macaddr "$wan_mac"
}

board_config_update
board=$(board_name)
ipq54xx_setup_interfaces $board
qcom_setup_macs $board
board_config_flush

exit 0
