#!/bin/sh

. /lib/functions.sh

board=$(board_name)

phy_dir="/sys/kernel/debug/ieee80211"
# Count the number of phyX
phy_count=$(ls -d $phy_dir/phy* 2>/dev/null | wc -l)
echo "$phy_count" > /tmp/phy_count

case "$board" in
    "edgecore,eap112")
        phy1_file=$phy_dir/phy1/mt76/sr_enable
        phy2_file=$phy_dir/phy2/mt76/sr_enable

        if [ -f "$phy1_file" ]; then
            check_phy1=$(cat $phy1_file)
            [ "$check_phy1" = 0 ] && echo 1 > $phy1_file
        fi

        if [ -f "$phy2_file" ]; then
            check_phy2=$(cat $phy2_file)
            [ "$check_phy2" = 0 ] && echo 1 > $phy2_file
        fi

        # note: phy0 is HaLow
        ln -sf $phy_dir/phy1/mt76/sr_scene_cond /tmp/sr_scene_cond_phy2g
        ln -sf $phy_dir/phy2/mt76/sr_scene_cond /tmp/sr_scene_cond_phy5g
    ;;
    "edgecore,eap111")
        phy0_file=$phy_dir/phy0/mt76/sr_enable
        phy1_file=$phy_dir/phy1/mt76/sr_enable

        if [ -f "$phy0_file" ]; then
            check_phy0=$(cat $phy0_file)
            [ "$check_phy0" = 0 ] && echo 1 > $phy0_file
        fi

        if [ -f "$phy1_file" ]; then
            check_phy1=$(cat $phy1_file)
            [ "$check_phy1" = 0 ] && echo 1 > $phy1_file
        fi

        ln -sf $phy_dir/phy0/mt76/sr_scene_cond /tmp/sr_scene_cond_phy2g
        ln -sf $phy_dir/phy1/mt76/sr_scene_cond /tmp/sr_scene_cond_phy5g
    ;;
    "edgecore,eap115"|\
    "edgecore,eap115a")
        band0_file=$phy_dir/phy0/mt76/band0/sr_enable
        band1_file=$phy_dir/phy0/mt76/band1/sr_enable

        if [ -f "$band0_file" ]; then
            check_band0=$(cat $band0_file)
            [ "$check_band0" = 0 ] && echo 1 > $band0_file
        fi

        if [ -f "$band1_file" ]; then
            check_band1=$(cat $band1_file)
            [ "$check_band1" = 0 ] && echo 1 > $band1_file
        fi

        ln -sf $phy_dir/phy0/mt76/band0/sr_scene_cond /tmp/sr_scene_cond_phy2g
        ln -sf $phy_dir/phy0/mt76/band1/sr_scene_cond /tmp/sr_scene_cond_phy5g
    ;;
esac
