#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

#start after dbus (60)
START=62
USE_PROCD=1

DEF_DIR="/etc/default"
LOG_DIR="/var/log"
RUN_DIR="/var/run"
SYSINFO_DIR="/var/sysinfo"
GPIO_DIR="/sys/class/gpio"

FW_DIR="/etc/ble_fw/ti"
FW_NCP="ble5_host_test_sdk8_3_bd9.bin"

DEV_VENDOR="$(cat $SYSINFO_DIR/board_name | awk -F, '{print $1}')"
DEV_MODEL="$(cat $SYSINFO_DIR/board_name | awk -F, '{print $2}')"

start_service() {
	config_load ble_chip

	config_get vendor $DEV_MODEL vendor
	config_get model $DEV_MODEL model
	config_get firmware $DEV_MODEL firmware
	config_get tty $DEV_MODEL tty
	config_get baudrate $DEV_MODEL baudrate
	config_get resetpin $DEV_MODEL resetpin
	config_get backdoorpin $DEV_MODEL backdoorpin
	config_get wdt_enabled $DEV_MODEL wdt_enabled
	config_get sw_rstpin $DEV_MODEL sw_rstpin

	case $(echo "$model") in
	CC2652R1)
		tichip="2652"
		;;
	esac

	tisbl.sh "$tty" "$baudrate" "$tichip" "$firmware" "$resetpin" "$backdoorpin" "$sw_rstpin"

	sleep 1

	if [ "$wdt_enabled" == "1" ]; then
		if [ "$(ps | grep '[w]dt_touch.sh')" ]; then
			wdt_touch.sh active
		else
			exec 1000>&-

			wdt_touch.sh >/dev/null 2>&1 &
		fi
	fi
}

reload_service()
{
	stop
	start
}

service_triggers()
{
	procd_add_reload_trigger "ble_chip" 
}
