#!/bin/sh /etc/rc.common

START=99

. /lib/functions.sh

gps_enable() {
	case "$(board_name)" in
	"edgecore,oap101"|\
	"edgecore,oap101e"|\
	"edgecore,oap101-6e"|\
	"edgecore,oap101e-6e")
		echo 0 > /sys/class/gpio/ble_enable/value
		echo 1 > /sys/class/gpio/gps_reset/value
		sleep 1
		echo 0 > /sys/class/gpio/gps_reset/value
		sleep 1
		# enable PAIR message to include Packet Type: 062 with GST (8 = NMEA_SEN_GST )
		echo "\$PAIR062,8,1*37" > /dev/ttyMSM1
		;;
	esac
}

gps_disable() {
	case "$(board_name)" in
	"edgecore,oap101"|\
	"edgecore,oap101e"|\
	"edgecore,oap101-6e"|\
	"edgecore,oap101e-6e")
		echo 1 > /sys/class/gpio/gps_reset/value
		echo 1 > /sys/class/gpio/ble_enable/value
		;;
	esac
}

start() {
	local disabled=$(uci get gps.@gps[-1].disabled)
	if [ "$disabled" -eq 1 ]; then
		gps_disable
	else
		gps_enable
	fi
}
