#!/bin/sh /etc/rc.common

START=80

boot() {
	. /lib/functions/system.sh
	case $(board_name) in
	edgecore,eap102)
		echo 54 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio54/direction
		echo 0 > /sys/class/gpio/gpio54/value
		echo 1 > /sys/class/gpio/gpio54/value
		btmgmt --index 0 static-addr FF:02:03:04:05:FF
		btmgmt --index 0 auto-power
		hciconfig hci0 up
		hcitool -i hci0 cmd 0x3f 0x006 
		;;
	esac
}
