#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1
PROG=/usr/bin/ieee8021x.uc

reload_service() {
	ubus call ieee8021x reload
	restart
}

service_triggers() {
	procd_add_reload_trigger ieee8021x
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
