#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1
PROG=/usr/sbin/ieee8021x

reload_service() {
	restart
}

service_triggers() {
	procd_add_reload_trigger ieee8021x
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance

	# add a dummy user DB until we have EAP-TLS support
	echo "\"bob\" MD5 \"hello\"" > /tmp/run/hostapd-ieee8021x.eap_user 
	echo "\"bob\" MD5 \"hello\" [2]" >> /tmp/run/hostapd-ieee8021x.eap_user 
}
