#!/bin/sh

. /lib/functions.sh

gen_uci_file_sonicfi_rap630w_311g(){
	local cfg_path=$1
	[ -z $cfg_path ] && cfg_path=/etc/config
	for num in $(seq 1 3)
	do
		uci -c ${cfg_path} add poe port
		uci -c ${cfg_path} set poe.@port[-1]='port'
		eval uci -c ${cfg_path} set poe.@port[-1].port_num='${num}'
		uci -c ${cfg_path} set poe.@port[-1].admin_mode='1'
	done
	uci -c ${cfg_path} commit

}

board=$(board_name)
case $board in
        sonicfi,rap630w-311g|\
        cybertan,eww631-b1)
		if [ ! -d /etc/config-shadow ]; then
			if [ ! -s /etc/config/poe ]; then
				touch /etc/config/poe
				gen_uci_file_sonicfi_rap630w_311g
			fi
		else
			if [ ! -s /etc/config-shadow/poe ]; then
				touch /etc/config-shadow/poe
				gen_uci_file_sonicfi_rap630w_311g /etc/config-shadow
			fi

			[ ! -f /etc/config/poe ] && cp /etc/config-shadow/poe /etc/config/poe
		fi
		;;
	*)
		;;
esac
