#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

mediatek_setup_interfaces()
{
	local board="$1"

	case $board in
	bananapi,bpi-r64-rootdisk|\
	bananapi,bpi-r64)
		ucidef_set_interfaces_lan_wan "lan0 lan1 lan2 lan3" wan
		;;
	mediatek,mt7622-rfb1)
		ucidef_set_interfaces_lan_wan "lan1 lan2 lan3 lan4" wan
		;;
	ubnt,unifi-6-lr)
		ucidef_set_interfaces_lan "eth0"
		;;
	*)
		ucidef_add_switch "switch0" \
				  "0:lan" "1:lan" "2:lan" "3:lan" "4:wan" "6u@eth0" "5u@eth1"
		;;
	esac
}

mediatek_setup_macs()
{
	local board="$1"
	local part_name="Factory"
	local lan_mac=""
	local wan_mac=""
	local lan_mac_offset=""
	local wan_mac_offset=""

	case $board in
	*)
		#512k - 12 byte
		lan_mac_offset="0x7FFF4"
		wan_mac_offset="0x7FFFA"
		;;
	esac

	lan_mac=$(mtd_get_mac_binary $part_name $lan_mac_offset)
	wan_mac=$(mtd_get_mac_binary $part_name $wan_mac_offset)

	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" "$lan_mac"
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" "$wan_mac"
}

board_config_update
board=$(board_name)
mediatek_setup_interfaces $board
mediatek_setup_macs $board
board_config_flush

exit 0
