#!/bin/bash

APP=`basename $0`
CURDIR=`dirname $0`

if [ $# -lt 1 ];
then
    echo "Usage: $APP <rootfs-path> [<build-descr>]"
    exit 1
fi

ROOTFS="$1"

# Source script that provides version data for image creation
source ${CURDIR}/version-lib.sh

VERSION_STAMP_FILENAME=${ROOTFS}/$VERSION_STAMP_DIR/.version
rm -f $VERSION_STAMP_FILENAME
echo "${APP_VERSION} (${USERNAME}@${HOSTNAME}) [${VER_DATE}]" > $VERSION_STAMP_FILENAME

${CURDIR}/version-gen matrix > ${ROOTFS}/$VERSION_STAMP_DIR/.versions

#
# stamp ssh banner
#
BANNER=${ROOTFS}/$VERSION_STAMP_DIR/etc/banner
if [ -e "$BANNER" ]; then
echo "Version : ${APP_VERSION}" >> ${BANNER}
echo "Built On: ${VER_DATE}" >> ${BANNER}
echo "Built By: ${USERNAME}@${HOSTNAME}" >> ${BANNER}
echo "********************************************************************" >> ${BANNER}
echo "" >> ${BANNER}
fi
