#!/bin/sh

. /lib/functions.sh

iface_del() {
        uci -c /etc/config-shadow/ delete wireless.$1
        uci -c /etc/config-shadow/ commit
}

[ "${ACTION}" = "add" ] && {
	/sbin/wifi config
	[ -d /etc/config-shadow ] && {
		cp /etc/config/wireless /etc/config-shadow/wireless
		config_load wireless
		config_foreach iface_del wifi-iface
		config_foreach iface_del wifi-vlan
	}
}
