#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0

. /lib/functions/caldata.sh

board=$(board_name)

case "$FIRMWARE" in
"ath9k-eeprom-pci-0000:01:00.0.bin")
	case $board in
	*)
		caldata_die "board $board is not supported yet"
		;;
	esac
	;;
esac
